### ISSUE TITLE
Only three types of heads useable

### ISSUE THREAD

**Issue by PropagandaTV** [Tachyonite/Pawnmorpher#100]
My game uses only three types of heads for creating colonists. The average normal, average pointy and the average wide head. If i remove pawnmorpher the game uses all types of heads to create new colonists. I have a big mod list but i tested it without any other mods too.

**To Reproduce**
I don't know how to reproduce the bug on other devices if it is working just fine on other Computers because its always showing up when i have the mod activated. But i get an error log when i load a colonist via EdB Prepare carefully who had one of the head types for example the narrow pointy head.

**Error Log**
[Prepare Carefully] Could not find a head type the graphic path: Things/Pawn/Humanlike/Heads/Male/Male_Narrow_Wide
Verse.Log:Warning(String, Boolean)
EdB.PrepareCarefully.Logger:Warning(String)
EdB.PrepareCarefully.CustomPawn:set_HeadGraphicPath(String)
EdB.PrepareCarefully.PawnLoaderV5:ConvertSaveRecordToPawn(SaveRecordPawnV5)
EdB.PrepareCarefully.PresetLoaderV5:Load(PrepareCarefully, String)
EdB.PrepareCarefully.PresetLoader:LoadFromFile(PrepareCarefully, String)
EdB.PrepareCarefully.Controller:LoadPreset(String)
EdB.PrepareCarefully.Page_PrepareCarefully:<DrawPresetButtons>b__32_0(String)
EdB.PrepareCarefully.Dialog_LoadPreset:DoMapEntryInteraction(String)
EdB.PrepareCarefully.Dialog_Preset:DoWindowContents(Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)

**Additional context**
I only get an error log from Prepare carefully when i load a colonist with a head type that isn't one of the tree i mentioned at the beginning. when i Play without any other mod exept Pawnmorpher the game is simply not using the other head types and i never get any error logs.
Hope you can understand it. My english skills are not the best.

**Comment by mc-oofy** [comment]
have you tried not using prepare carefully

**Comment by FxWolfxe** [comment]
the error is caused by an incompatibility with Prepare Carefully and narrow heads not showing up is by design
