### ISSUE TITLE
[Pawn_Name] or something like that

### ISSUE THREAD

**Issue by mc-oofy** [Tachyonite/Pawnmorpher#102]
for example on the hediff Conflicted Mind the description has stuff like (somewhat like) [Pawn_Name],[Pawn_Pronoun] (which i think doesnt work on hediffs)
also some descriptions on items and others start with a lowercase letter

also morphs when selected from "View: (name)morph" have their descriptions something like this:
"!!!(name) is missing description!!!" or something like that

**Comment by FxWolfxe** [comment]
this is a known issue with 1.1 version of rimworld and how it get Hediff descriptions. This isn't something that can be fixed on our end right now

**Comment by mc-oofy** [comment]
maybe do something like "This pawn has"

**Comment by FxWolfxe** [comment]
we use the grammar rules in our own tooltips plus the devs may be changing how they get hediff descriptions in the future
