### ISSUE TITLE
[Dev Build] No sapience gain on reverted pawns.

### ISSUE THREAD

**Issue by lucastherrien** [Tachyonite/Pawnmorpher#114]
**Describe the bug**
The sapience of reverted former human paws seems static at the moment, it doesn't appear to regenerate over time.

**To Reproduce**
1. Turn pawn into animal
2. Revert pawn
3. Watch sapience bar for 5 or so minutes

**Expected behavior**
Reverted pawns are supposed to gain sapience, right? Otherwise how are the pawns supposed to gain sapience?

**Comment by FxWolfxe** [comment]
this has been fixed in 2d7e6b501daf3be17685578779407d038f323435
