### ISSUE TITLE
Former Animals in manhunter packs can open doors

### ISSUE THREAD

**Issue by Omen267901** [Tachyonite/Pawnmorpher#116]
**Describe the bug**
Former humans that are in Manhunter state are able to open doors and do not obey standard Manhunter rules (they seem to instead act like a Raider, although Raiders still can't open doors). This is absolutely devastating if you get a Manhunter pack of Chaomorphs, as they are extremely powerful and almost unstoppable in these quantities, and can walk straight through your defenses (even death corridors and killboxes are useless)

**To Reproduce**
1. Get a manhunter pack with Former Humans in it, preferably Chaomorphs
2. Hide indoors.
3. Watch them walk right on in uninvited

**Error Log**
https://gist.github.com/b811a6fa3aaa239d7ece33e107afff93

**Expected behavior**
Either the game to give you a warning ahead of time that this is something that can happen (if this is intended behavior), or for them to respect standard Manhunter rules.

**Screenshots**
https://i.imgur.com/JRwRjnG.png

**Additional context**
As far as I'm aware, none of my other mods should be affecting pathfinding or doors to potentially cause this. I also found a reddit post about this from last week, though it seemingly wasn't reported here

**Comment by FxWolfxe** [comment]
fixed by 64d1a4f5543aeccb945cb99db8e7016432c06235
