### ISSUE TITLE
Chaomelds spawned in the wild only has a single "Former human"

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#119]
**Describe the bug**
Any chaomelds that spawn either wild or as a raid only have a single "former human" and become a single pawn when reverted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Have any chaomeld get spawned by the game (not through chamber)
2. Tame and revert chaomeld
3. Chaomeld becomes a single pawn

**Expected behaviour**
Chaomelds are supposed to be "2x former human" and become 2 pawns when reverted.

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/82761072-21a2f780-9df8-11ea-9140-cea1bbdb684a.png)

**Comment by FxWolfxe** [comment]
this is fixed by f6304ab7cb6e5da82b4803a9189e80d6c5ff909d
