### ISSUE TITLE
[Dev] Animal selector comp not working

### ISSUE THREAD

**Issue by lucastherrien** [Tachyonite/Pawnmorpher#124]
**Describe the bug**
So it seems the animal selector comp for the mutagun isn't doing anything right now. The button itself is working as intended, but the gun is still firing regular ethermorph projectiles, not actually turning people into the desired animal. To be clear, I commented out my attempts to get this to work with turrets to see if that was the issue and rebuilt the mod. Still didn't work.

**To Reproduce**
1. Give pawn mutagun or select animal whilst gun is on ground
2. Give pawn mutagun or select animal whilst gun is equipped, whichever you didn't do first
3. Fire mutagun at test subjects, I used 3 colonists for convenience and to make sure it was consistently not working
4. test subject pawns will change into random animal

**Expected behavior**
pawns should change into animal set by the animal selector comp

**Comment by FxWolfxe** [comment]
should be fixed by commit 3de6762d7ff7c95e85c1499c94518c7cbd98d22a

**Comment by FxWolfxe** [comment]
should be fixed in latest release
