### ISSUE TITLE
Mod conflict : A RimWorld of Magic

### ISSUE THREAD

**Issue by vlad1492** [Tachyonite/Pawnmorpher#126]
When using Mutaserum, reverter on a mage their class XP is reset to zero and skills/spells are lost.

**Comment by FxWolfxe** [comment]
can you post a log with hugs lib after the bug happens?

**Comment by vlad1492** [comment]
Yes, here is the link.  Workaround is to use God Mode and open the magic tab, add back in the lost levels. Then dev mode to provide scrolls for the lost spells.  

https://gist.github.com/b97838d1b44147edf1a84dbdee4f5afd

**Comment by vlad1492** [comment]
Note- I tested it on an unmodified human mage and a mutant, only the mutant lost his powers.

**Comment by FxWolfxe** [comment]
this doesn't look like something that can be fixed on our end unfortunately
