### ISSUE TITLE
Conflict with Hardworking animals 1.1

### ISSUE THREAD

**Issue by AfxousaAjagara** [Tachyonite/Pawnmorpher#128]
**Describe the bug**
So far, there hasn't been a problem situation, but every time I start the game, the error occurs.

**To Reproduce**
Conflict with Hardworking animals 1.1, so you just need to install that mod to reproduce.

**Error Log**
[Hardworking animals 1.1] Patch operation Verse.PatchOperationReplace(*/ThinkTreeDef[defName = "Animal"]/thinkRoot/subNodes/li[18]/subNodes/li[3]) failed
file: D:\Games\Steam\steamapps\workshop\content\294100\933324235\1.1\Patches\HardWA.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Expected behavior**
Animal should have to move object more often, but it isn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/43234489/87299431-f8286180-c546-11ea-9fc2-cfa1bf90333d.png)

**Additional context**

**Comment by FxWolfxe** [comment]
this is due to the way they are patching the think tree def. This isn't something we can fix on our end, it will have to be fixed on theirs
