### ISSUE TITLE
Pawnmorpher and Forsaken mod body size error

### ISSUE THREAD

**Issue by Gawain-byte** [Tachyonite/Pawnmorpher#130]
**Describe the bug**
Hello Mic, I recently encountered a bug between the Pawnmorpher and Forsaken mod. Basically, I reverted a boomrat former human, back into a forsaken and the hunger rate stayed the same. So instead of the nutrition being .6 it's .2 . I now believe that this error is caused by the body size not reverting back to normal forsaken race size. I have encountered this with other former humans types, as well as chaomelds.

**Comment by FxWolfxe** [comment]
It doesn't look like there is anything we can do from our end
