### ISSUE TITLE
Multiplayer Compatibility

### ISSUE THREAD

**Issue by notfood** [Tachyonite/Pawnmorpher#181]
Multiplayer compatibility has been commented out, after a review, there was a lot of unneeded things. I made a patch that only requires one file and has exactly just what is needed. I'll make a PR to remove all the misleading multiplayer comments as well.

**Comment by Tachyonite** [comment]
Please raise the PR with your changes and we can likely include it in the hotfix we'll need to do fir the latest RW update.
