### ISSUE TITLE
Rendering Issue between Pawnmorpher and FemaleBB BodyType Support

### ISSUE THREAD

**Issue by MrCreeperAG** [Tachyonite/Pawnmorpher#190]
**Describe the bug**

**To Reproduce**
Install FemaleBB BodyType Support alongside Pawnmorpher
Have a Pawn with FemaleBB Body become a morph

**Expected behavior**
The Pawnmorpher additions to render in the correct position

**Screenshots**
https://imgur.com/a/wJb0rKy

**Additional context**
Load Order can be found in the Imgur Album.

**Comment by FxWolfxe** [comment]
this is because FemaleBB modifies/replaces the vanilla bodies for some pawns. This isn't something we can fix on our end
