### ISSUE TITLE
Mutagenic Shells and Combat Extended compatibility issue

### ISSUE THREAD

**Issue by Eqlipse** [Tachyonite/Pawnmorpher#194]
When playing with Combat Extended and Pawnmorpher, one is unable to load mutagenic shells into the mortar. Combat Extended replaces the vanilla mortar with "81mm mortar," and uses a slightly different method for loading them, involving a UI button that's a large improvement over the standard vanilla method. 

However, said UI does not list the Mutagenic Shells as an option.

1. Install both Pawnmorpher and Combat Extended
2. Click on 81mm mortar's shell selection button
3. Mutagenic shell will fail to show in the listing.

Unfortunately, I can't really take a screenshot of this, as pressing the print screen button (or any button, really) closes the menu I'm talking about.

**Comment by FxWolfxe** [comment]
this and other problems related to combat extended are known issues. There are currently no plans to implement full combat extended compatibility on our end
