### ISSUE TITLE
Cannot order former human (mostly sapiet) pawn to hospital bed

### ISSUE THREAD

**Issue by Eqlipse** [Tachyonite/Pawnmorpher#195]
Normally, when a pawn gets sick or is injured, you can order them to "rest until healed." This is important when they need to receive treatment from a doctor with enough skill, especially for critical injuries. 

However, for the former human pawns - which you can still exert manual control over - this is not the case: I've lost more than one of them due to them being too stupid to go and lie down on a hospital bed on their own. 

One particularly silly lynx played poker until she bled-out and had to be rescued -_- I can still "draft" them, and order them to stay in the hospital until they need rescuiing, but I cannot order them to go and stay there until healed or operated on.

**Comment by FxWolfxe** [comment]
should be fixed in 1.10.0
