### ISSUE TITLE
Unable to remove arm type; wing

### ISSUE THREAD

**Issue by Eqlipse** [Tachyonite/Pawnmorpher#196]
It seems that the armtype, wing, tends to get "stuck" on a pawn. For example, if the left arm is "wing," then no matter how many times you inject that pawn with panther, rabbit, or other serums, it will _never_ revert back to a normal arm type.

What's worse, after fully reverting a pawn to human (with a mutaserum reverter), and _then_ injecting them with some non-wing-bearing mutagen (lynx, for example), the arm will change back into a wing again.

Considering that the one thing which _does_ seem to change the arm-type is the pawnmorpher insects mod (which has the only other set of mutations that actually change the arm-type - to insectoid), I suspect this has something to do with the fact that no other mutation affects the "arm," aside from adding fur or scales or such.

A lingering result is that, when a pawn starts to undergo a mutation again from human, the wing arm-type descriptor is still there, because nothing removed it.

Steps to reproduce:
1. Allow pawn to get "wings" for arms.
2. Attempt to change this by using mutaserums for other species (lynx, panther, hare, snowhare, and fox (all of them) are the ones I used). Regardless of the number of attempts, or even the usage of acceleration pills, it remains stuck as "wing."
3. Attempt to bypass this by fully reverting pawn to human, _then_ changing them into the desired species. This still fails, as the wing(s) will suddenly show up again.

**Comment by FxWolfxe** [comment]
this should be fixed in the latest build
