### ISSUE TITLE
Mutaserum, reverter breaks/resets modifications in pawns from other mods

### ISSUE THREAD

**Issue by Patryk-S-W** [Tachyonite/Pawnmorpher#203]
After using Mutaserum, reverter:
- Rim of Madness - Vampires:
Vampirism (Bloodline, Sire, Childer), Generation is set to Unknown, None and NULL
- Rim of Magic
XP Gain, Level, Points and spells are reset to 0

- broken Tab Health UI on the pawn, needs save&load to bring back functionality

https://gist.github.com/HugsLibRecordKeeper/2afd114abff9c8b076d6bf56160afb8f

**Comment by FxWolfxe** [comment]
The incompatibility with Rim of Magic is a known issue that unfortunately doesn’t appear to have a solution on our end and I suspect the same will be true of Vampires but I will look into it

**Comment by FxWolfxe** [comment]
this doesn't look like something that can be fixed on our end unfortunately
