### ISSUE TITLE
Mod conflict: Kurin, Three tailed foxes (Alien Framework version), Eccentric Tech - Cosmetic Modifications

### ISSUE THREAD

**Issue by Patryk-S-W** [Tachyonite/Pawnmorpher#204]
- Kurin, Three tailed foxes (Alien Framework version)
Kurins receive mutations in Health Tab but they are not visible directly on the pawn

- Eccentric Tech - Cosmetic Modifications:
Bionic Replacements become invisible on the pawn during mutation (duplication of body parts and only one displayed) regardless of whether bionics added before or during mutation

I know its problem on the alien framework side (only one HeDiff can be seen) but it can be solved with visibility priorities:
-- bionics parts > mutations parts > race parts
-- or surgeon priority (newest -> visible)

**Comment by FxWolfxe** [comment]
the first is by design, only humans will have mutation graphics unless the race modder adds a compatibility patch on their end to add the necessary graphics and offsets for their race. The second issue is as you said, something that would have to be changed in HAF not on our end
