### ISSUE TITLE
Some 'pure' morphs don't reach the correct thought stage for mutation affinity/body purist traits (Dev)

### ISSUE THREAD

**Issue by lucastherrien** [Tachyonite/Pawnmorpher#206]
**Describe the bug**
Some 'pure' morphs with mutation affinity/ (such as wolfmorphs and cobramorphs) are failing to reach the 'morph overjoyed' (or body purist equivalent) thought stage.

**To Reproduce**
1. Have a 'pure' wolfmorph/cobramorph with mutation affinity/body purist in colony
2. Click on needs tab for that pawn
3. The thought stage for their possessed trait will be lower than it was in the previous update

**Expected behavior**
After a colonist with one of these traits recieves all the mutations from any mutasyringe/serum, they should reach the correct (according to the code, stage No.4) thought stage.

**Comment by FxWolfxe** [comment]
fixed in latest version
