### ISSUE TITLE
New colonies can start with hellhounds

### ISSUE THREAD

**Issue by BrennenCramer** [Tachyonite/Pawnmorpher#272]
**Describe the bug**
Hellhounds are available to be selected as one of the random starting animals in new playthroughs.

**To Reproduce**
Keep starting new playthroughs till you start with one with one.

**Expected behavior**
Since hellhounds are supposed to be only obtainable through the use of luci, this is another obtainment method we need to forbid.

**Screenshots**

**Additional context**
Was done with bare minimum load order (PM, HAR, Core, Harmony, Royalty, Hugslib), Might be less of a problem if other creature mods are installed, but is still a problem.  
I am leaving this here b/c I am too busy IRL atm to fix it myself, sorry Iron/Yap.

![RimWorldWin64_FFSqyDd4wO](https://user-images.githubusercontent.com/48333768/99136904-82a7cd00-25dc-11eb-8c9e-0bcf10048f33.png)

**Comment by FxWolfxe** [comment]
fixed in latest version
