### ISSUE TITLE
pawns can't eat

### ISSUE THREAD

**Issue by DeManteYast** [Tachyonite/Pawnmorpher#273]
**Describe the bug**
Pawns and animals can't eat.  Wild animals will kill a creature and then munch on it forever and not actually eat it.  Pawns will eat something but when done, will drop it and the food meter will remain the same.

**To Reproduce**
I thought it might have been other mods interacting with this one, so I dropped all mods except the dependencies.  I'm still getting the same result. 
I'm on game version 1.2.2753

**Expected behavior**
I expect things to eat.

**Comment by FxWolfxe** [comment]
can you post the hugslib log, this should be fixed for the current version of PM and HAR

**Comment by DeManteYast** [comment]
Sorry for the late reply,  It was fixed in the latest patch.  Thanks!  It's a great mod!
