### ISSUE TITLE
Pawnmorpher with FemalBB BodyType

### ISSUE THREAD

**Issue by Gentaei** [Tachyonite/Pawnmorpher#274]
Using Pawnmorpher with Female BB Body Type breaks the offset for the Morp Parts. They are all misaligned.

**To Reproduce**
1. Use Pawnmorpher
2. Use FemalBB BodyType Support and FemalBB BodyType for Human
3. Spawn a New Colonist with BB Body with Morph parts. Ears, Horns, Snout, Tail etc.
4. All Parts are misaligned on all directions. Loadorder does not affect it.

Morph Parts should work correctly with FemalBB BodyType, maybe needs a patch to fit correctly to the BB Body.
![femal_bb](https://user-images.githubusercontent.com/20024375/99886079-fc256800-2c39-11eb-9051-da2d241888c8.png)

**Comment by FxWolfxe** [comment]
this is an issue with FemalBB's graphics and can't be fixed on our end
