### ISSUE TITLE
Feline Hands don't adapt

### ISSUE THREAD

**Issue by lucastherrien** [Tachyonite/Pawnmorpher#275]
**Describe the bug**
Pretty much what the title says

**To Reproduce**
1. Give pawn feline hands
2. No matter how long you wait or whether a pawn has been given accelerator and/or is paragon, feline hands will never adapt their initial stage

**Expected behavior**
The hands should adapt like every other mutation

**Comment by FxWolfxe** [comment]
fixed in latest version
