### ISSUE TITLE
Mutation Sequencer can't be used indoors (Dev)

### ISSUE THREAD

**Issue by lucastherrien** [Tachyonite/Pawnmorpher#276]
**Describe the bug**
Pretty much what the title says

**To Reproduce**
1. Place mutation sequencer under a roof
2. Game will throw an alert saying 'building unusable due to roof' and the sequencer will be unusable

**Expected behavior**
Given it's a piece of laboratory equipment, it should be usable indoors

**Comment by FxWolfxe** [comment]
fixed in latest version
