### ISSUE TITLE
Pawn Mutations stopped appearing on the mutations tab

### ISSUE THREAD

**Issue by lizardwizard789** [Tachyonite/Pawnmorpher#287]
Pawn mutation percentages stopped showing on the mutations tab, instead showing a pawn that is roughly 57% boomamorph as being 100% human.  chemical cyst also stopped appearing in the production column.  all mutations persist in the health tab.  pawn does not consider itself mutated (i.e. doesn't get mood boosts from mutation affinity trait)
**To Reproduce**
1. mutate a pawn (not sure how specific this is but i used a baseline human mutated to about 60% boomamorph)
2. administer mutagen stabilizer pills
3. save and reload
4. presto chango its broken and sad

**Error Log**
https://gist.github.com/5556e732853e4e48325e3029f9676b23

**Expected behavior**
the pawn remains 57% boomamorph and gains all the benefits of being so.

**Additional context**
i have prepare carefully loaded but haven't used it at all.

**Comment by FxWolfxe** [comment]
should be fixed in the latest release
