### ISSUE TITLE
Mod disables right-click prompts

### ISSUE THREAD

**Issue by Meti172172** [Tachyonite/Pawnmorpher#289]
**Describe the bug**
Adding the Pawnmorpher mod causes logs to go crazy, completely disables right-click actions, with them only working when colonists are drafted. Also as an oddity, when pressing the "Social" tab of colonists the menu starts flickering. Tried rearranging mods to no avail.

**To Reproduce**
1. Go to 'A game with the mod on'
2. Click on '.A colonist'
3. Click 'literally any normally interactable item'

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/f3273fd6abf49f80f8833cf8dc69b4c4

**Expected behavior**
Right click prompts to work

**Comment by FxWolfxe** [comment]
you're missing the required assembly to load the mod. if you got this from github you have to build the mod yourself
