### ISSUE TITLE
The bug, appearing in log, when starting new game.

### ISSUE THREAD

**Issue by Kasev-92** [Tachyonite/Pawnmorpher#293]
**Describe the bug**
That appears, when starting new game.

**Error Log**
[MVCF] Found equipment with more than one ranged attack while that feature is not enabled. Enabling now. This is not recommend. Contact the author of Pawnmorpher and ask them to add a MVCF.ModDef.
Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
MVCF.Utilities.VerbManagerUtility:AddVerbs(VerbManager, ThingWithComps)
MVCF.Harmony.Trackers:EquipmentAdded_Postfix(ThingWithComps, Pawn_EquipmentTracker)
Verse.Pawn_EquipmentTracker:Verse.Pawn_EquipmentTracker.Notify_EquipmentAdded_Patch3(Pawn_EquipmentTracker, ThingWithComps)
Verse.ThingOwner:NotifyAdded(Thing)
Verse.ThingOwner`1:Verse.ThingOwner`1[[Verse.Thing, Assembly-CSharp, Version=1.2.7705.25110, Culture=neutral, PublicKeyToken=null]].TryAdd_Patch1(ThingOwner`1, Thing, Boolean)
Verse.Pawn_EquipmentTracker:Verse.Pawn_EquipmentTracker.AddEquipment_Patch3(Pawn_EquipmentTracker, ThingWithComps)
RimWorld.PawnWeaponGenerator:RimWorld.PawnWeaponGenerator.TryGenerateWeaponFor_Patch5(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:Verse.PawnGenerator.GenerateGearFor_Patch4(Pawn, PawnGenerationRequest)
Verse.PawnGenerator:Verse.PawnGenerator.TryGenerateNewPawnInternal_Patch0(PawnGenerationRequest&, String&, Boolean, Boolean)
Verse.PawnGenerator:GenerateNewPawnInternal(PawnGenerationRequest&)
Verse.PawnGenerator:GenerateOrRedressPawnInternal(PawnGenerationRequest)
Verse.PawnGenerator:Verse.PawnGenerator.GeneratePawn_Patch8(PawnGenerationRequest)
RimWorld.ThingSetMaker_MapGen_AncientPodContents:GenerateIncappedAncient()
RimWorld.ThingSetMaker_MapGen_AncientPodContents:Generate(ThingSetMakerParams, List`1)
RimWorld.ThingSetMaker:RimWorld.ThingSetMaker.Generate_Patch1(ThingSetMaker, ThingSetMakerParams)
RimWorld.BaseGen.SymbolResolver_AncientCryptosleepCasket:Resolve(ResolveParams)
RimWorld.BaseGen.BaseGen:Resolve(Element)
RimWorld.BaseGen.BaseGen:Generate()
RimWorld.GenStep_ScatterShrines:ScatterAt(IntVec3, Map, GenStepParams, Int32)
Verse.GenStep_Scatterer:Generate(Map, GenStepParams)
Verse.MapGenerator:GenerateContentsIntoMap(IEnumerable`1, Map, Int32)
Verse.MapGenerator:GenerateMap(IntVec3, MapParent, MapGeneratorDef, IEnumerable`1, Action`1)
Verse.Game:Verse.Game.InitNewGame_Patch2(Game)
Verse.<>c:<Start>b__1_2()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Expected behavior**
If it's possible, better to resolve that problem.

**Comment by FxWolfxe** [comment]
should be fixed in the latest release
