### ISSUE TITLE
Mutagen Chamber - Part Picker errors

### ISSUE THREAD

**Issue by SailingPlane** [Tachyonite/Pawnmorpher#295]
When trying to use part picker there is the ability to change parts but no ability to confirm and everything is shifted to the left side of the pop-up. 

1. Enabled god mode.
2. Spawned chamber and part necessary to operate.
3. Place pawn in the chamber and try to use mutation part picker, with or without god mode.
4. Error appears in log continuously until the part picker is exited. (Literally saw 25,000+ of the same error.)

Log using Ctrl+F12:
https://gist.github.com/HugsLibRecordKeeper/0a213be92d09cd72b77413999e8fceb8

Honestly, this is my first time using the chamber and pawnmorpher in general, so I don't know what it's supposed to look like but it isn't working at the very least. Even with a very stripped down load order.

**Comment by SailingPlane** [comment]
Needless to say all of the above occurs even if I research all tech and go about doing this without god mode.

**Comment by FxWolfxe** [comment]
this should be fixed in the current release
