### ISSUE TITLE
A weird couple of former humans

### ISSUE THREAD

**Issue by GuakeTheDragon** [Tachyonite/Pawnmorpher#297]
Accidentally just after auto-save there appiered a couple of former humans as Chao- versions, and sometimes some of them even have relations to my currently pawns, but i can't find them on the map (the game shows me the world map where my colony is, but not the exact location in my colony). Also they became my own pawns as well when spawned, and my game begin to lag to 20-30 tps after this happen. I tried to load one of a previous save files, but this happen even to them now! I worry that i may corrupt every file this way.

A moment before the bug:
https://gist.github.com/GuakeTheDragon/f7b1d9bfbb9857a3fd49237bc9af8e0f

After a second:
https://gist.github.com/GuakeTheDragon/2ce5d62d4806e0f663b25c2863cabf81

Don't know if i should to put a screenshot here
![weirdRIMWORLD](https://user-images.githubusercontent.com/49972308/120079058-95f03500-c0f5-11eb-8b01-aba8677f91c1.png)

**Comment by RadHazard** [comment]
This is almost certainly related to the bug where former humans in trade ships can auto-join the colony.  This should be fixed once #353 makes it into the public build.
