### ISSUE TITLE
Grazing Sentient Animals will bring plants to a table and plant them under the table when finished.

### ISSUE THREAD

**Issue by DrewTuber** [Tachyonite/Pawnmorpher#310]
Using the mod [[Kit] Graze up](https://steamcommunity.com/sharedfiles/filedetails/?id=2302739121) results in many types of plants being deposited under tables when grazing sentient animal pawns bring their food to a table. There is a no limit to the number of plants that will stack up, and before long you end up with dozens of plants on a single tile, growing on wood floors under the dining room table.

The creator of Graze Up seems to believe that this is purely a PawnMorpher problem, and is out of their control.
![image](https://user-images.githubusercontent.com/9029918/124360102-33c0ad80-dc28-11eb-8aa6-93706af6d49e.png)

Here is an example of the problem, with the mouse cursor over a tile under the table. You can see the previous plants my grazing morphs have brought inside selected for cutting. Unfortunately if there are 20 plants on a single tile, you have to select it for cutting 20 times, as pawns will only remove them one at a time, "completing" the cut order.
![image](https://user-images.githubusercontent.com/9029918/124359992-a54c2c00-dc27-11eb-9ed2-2279b1ca3cd7.png)

While this bug technically does not effect gameplay, it does look quite awful to see your dining room overgrown with various plants.

Here is my main man Hahn "planting" some grass during his meal.
![image](https://user-images.githubusercontent.com/9029918/124360199-ce20f100-dc28-11eb-844a-d3db4855ce0b.png)

**Comment by ariscop** [comment]
Seen former humans in caravans carrying plants, not using graze up

**Comment by Diakon5** [comment]
In Latest Dev version and newest Graze up!, appears to not happen. Sentient animals don't pick up grass to be eaten, checked at most levels of sapience.

Forcing a pawn to eat grass does raise a red error due to a lack of comps on grass

**Comment by Zeracronius** [comment]
Best case would be for plants should die off instead of getting planted.

**Comment by Zeracronius** [comment]
Sapient former human brings food to nearby table if any as per pawn behaviour. Graze up! is what can cause the plants to remain since the animal might not eat the entire plant.

**Comment by Diakon5** [comment]
> Sapient former human brings food to nearby table if any as per pawn behaviour. 

My testing showed that Sapient Former Humans don't take grass to the table.

**Comment by Diakon5** [comment]
Testing on the latest Dev Build:

Default: Sapient Former Humans bring grass to table, eat it whole, Pawn-like behavior
[[Kit]Graze up](https://steamcommunity.com/sharedfiles/filedetails/?id=2302739121): Sapient Former Humans eat grass on the spot, never picking it up. Animal Behavior
[Grazing Lands](https://steamcommunity.com/sharedfiles/filedetails/?id=1770268130): Sapient Former Humans bring grass to table, and drop it after eating, as per issue.

With mods loaded before or after Pawnmorpher, the behavior was consistent. The issue happens with Grazing Lands, not [Kit]Graze up. However, the latter might still contain a patch that could serve as a fix.

**Comment by Zeracronius** [comment]
Since this issue is no longer a problem with Graze up, I will close this issue.
