### ISSUE TITLE
Incompatible with Female BB.

### ISSUE THREAD

**Issue by Raptor2213** [Tachyonite/Pawnmorpher#311]
Whenever this mod loads a busty female, the animal overlay breaks, and you have a random half a face and/or tail just floating in midair.

**Comment by FxWolfxe** [comment]
with the way Beter Body works this isn't something we can fix

**Comment by Raptor2213** [comment]
> with the way Beter Body works this isn't something we can fix

Wasn't necessarily asking for a fix (though it would be nice).  Just providing information.  Can it at least be added to the list of mods this one is incompatible with?
