### ISSUE TITLE
Animalistic humanoid pawns (mostly feral, feral) neither sleep nor eat.

### ISSUE THREAD

**Issue by c0rpx** [Tachyonite/Pawnmorpher#323]
Animalistic humanoid pawns (mostly feral, feral) neither sleep nor eat.

Mods loaded: Only the required (Harmony, Core, Hugslib, Humanoid Alien Races, Pawnmorpher (Mod Manager))

1. Start New Game
2. Reduce Sapience of Pawn (Through feral pills or dev tool)
3. See them switch to animal tab and starve/collapse

**Error Log**
There is no real Error Log showing up when this happens.

**Expected behavior**
Feral humanoid pawns should eat and sleep and otherwise roam about.

**Screenshots**
![RimWorld1](https://user-images.githubusercontent.com/88160539/127639922-3cc5ba27-2d6c-4fe3-8776-8ddceaa6ead0.jpg)

**Additional context**
After Pawns are able to produce something (Chook or Cowmorph stuff) the Sapience can be reduced via feral pills. It should make them easy to manage (Animal behavior, less needy). Maybe this is not even intended to work like that, but a feral humanoid pawn should at least be able to find something to eat like an animal, too? I know varieties of this have supposedly been fixed in the past, but this behavior seems to persist even without other mods loaded.

**Comment by FxWolfxe** [comment]
fixed in latest release
