### ISSUE TITLE
Split mind is missing a description.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#403]
The split mind aspect does not have a description.

![billede](https://user-images.githubusercontent.com/64704191/149802680-feeb3707-2f89-4f9a-8a85-1f500c56aef8.png)

**Comment by FxWolfxe** [comment]
marking as low priority, I don't believe split mind is currently used anywhere atm

**Comment by Zeracronius** [comment]
A tester reported it, so should probably look into and remove any current use.

**Comment by Zeracronius** [comment]
Split mind is currently getting added if meld is a combination of MutationAffinity and BodyPurist.
