### ISSUE TITLE
Former human hellhounds doesn't handle drugs properly.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#417]
**Describe the bug**
"drug purposes hellhounds seem to be animals rather than former humans."

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/918940315430289418

**Comment by lelodu87** [comment]
Issue confirmed and completed: wargs and hellhounds don't have the option to consume some (all?) drugs.

Likely related to specific diet.
![unknown](https://user-images.githubusercontent.com/86140855/153659350-6140ec77-cfa5-439f-84b0-12df6b6793ca.png)

**Comment by Zeracronius** [comment]
Wargs and Hellhounds share food type "CarnivoreAnimalStrict" which *only* allows "Meat" and "Corpse".
Since drugs are neither, a hellhound (or warg) will not even get the option to ingest. It is still possible to administer drugs, but it seems that completely sidesteps food typing since that happens through operations.
