### ISSUE TITLE
Powerful species injectors do not give powerful mutations.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#433]
**Describe the bug**
Injectors for species like Elephant does not cause powerful mutations like Bellowing lungs.

**Comment by Zeracronius** [comment]
Powerful morphTFs need to be marked with <allowAllRestrictedParts>True</allowAllRestrictedParts>

**Comment by FxWolfxe** [comment]
How restrictions work on morphs should be looked at again. Morphs that are a part of a restricted category should implicitly allow mutations from those categories by default, just not other categories they are not a part of themselves

**Comment by Zeracronius** [comment]
Category as i understand them currently only exist for serums and has no relation to animalclasses.
There is no relation between "Powerful" category and "Powerful" class of which the mutations are part of.
The problem is that the powerful mutations of the powerful class is set to restricted, so without allowing restricted the powerful morphs won't get them despite being part of the powerful class

**Comment by FxWolfxe** [comment]
Kinda. Classes are for the hierarchy and influence calculation and do not determine restrictions themselves, categories do. Morph categories have an `associatedMutationCategory` field that could be used to link morph categories with mutation categories, and from there make sure associated morph mutations make sure to include those mutations
