### ISSUE TITLE
Former human ritual count

### ISSUE THREAD

**Issue by lelodu87** [Tachyonite/Pawnmorpher#480]
**Describe the bug**
Former humans do not count as participants for some rituals.

**Comment by ArkiveDev** [comment]
I'm unable to perform a ritualistic scarring ritual on a former human. Message on the disabled ritual: "Disabled: You need the person to scarify to start..."

**Comment by lelodu87** [comment]
Confirmed.

Roles changes: former humans count as participants.
Skylantern: former humans do not count.

There're probably more rituals with the issue. Could not test everything.

**Comment by Diakon5** [comment]
Did some testing. On a skim, only scarification and blinding rituals don't accept former humans
