### ISSUE TITLE
Heroes Requiem considers a pawn dead after reversion

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#487]
**Describe the bug**
Heroes Requiem considers a pawn dead after reversion. In this case Ramsey

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/154300073-d7664ffe-49a6-4a59-bc15-574180169fb7.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/943244230783033365

**Comment by Zeracronius** [comment]
Error while notifying ideos of a HistoryEvent: System.ArgumentException: Could not find arg named TransformedPawn of type Pawn at RimWorld.SignalArgs.GetArg[T] (System.String name) [0x0002c] in <81af9f8a18324e17b286924a43555a7c>:0 at Pawnmorph.HistoryEventUtilities.GetArg[T] (RimWorld.HistoryEvent ev, System.String label) [0x00001] in <ba97cd4575a343dabcf2e914dacb9bce>:0 at Pawnmorph.PreceptComps.VeneratedAnimalTransformation.GetAnimal (RimWorld.HistoryEvent& historyEvent, RimWorld.Ideo ideo) [0x00001] in <ba97cd4575a343dabcf2e914dacb9bce>:0 at Pawnmorph.PreceptComps.VeneratedAnimalMemory.Notify_MemberTookAction (RimWorld.HistoryEvent ev, RimWorld.Precept precept, System.Boolean canApplySelfTookThoughts) [0x0004a] in <ba97cd4575a343dabcf2e914dacb9bce>:0 at RimWorld.Ideo.Notify_MemberTookAction (RimWorld.HistoryEvent ev, System.Boolean canApplySelfTookThoughts) [0x00031] in <81af9f8a18324e17b286924a43555a7c>:0 at RimWorld.IdeoUtility.Notify_HistoryEvent (RimWorld.HistoryEvent ev, System.Boolean canApplySelfTookThoughts) [0x00042] in <81af9f8a18324e17b286924a43555a7c>:0 at RimWorld.HistoryEventsManager.RecordEvent (RimWorld.HistoryEvent historyEvent, System.Boolean canApplySelfTookThoughts) [0x00000] in <81af9f8a18324e17b286924a43555a7c>:0 (Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by Diakon5** [comment]
Happens only on reversion from animal to humanlike. Possible cause is the discarding of animal.
Bonded Animals can cause funeral obligations, related?
