### ISSUE TITLE
Lopsided Morphs

### ISSUE THREAD

**Issue by TheARate** [Tachyonite/Pawnmorpher#50]
I've got a pawn that I morphed purely with cowmorph milk. She's got every part except for a left hand hoof, right foot hoof, and both horns. As she drinks more milk, she gains more partials, but the partials haven't added anything else, they just go away. I've had this issue for a while now, and she just hasn't changed from this point.
Here's a screenshot of some of the hediffs:
![20200221221133_1](https://user-images.githubusercontent.com/53186958/75085456-7c763b80-54f7-11ea-897a-63cfffa984aa.jpg)

Update: It seems that this isn't the only case. I have another morph who I only used chookmorph eggs on. Same story, but different parts.

**Comment by FxWolfxe** [comment]
this should be fixed with the latest version of HAF
