### ISSUE TITLE
[Feature, minor] Compatibility with Vanilla Backgrounds Expanded

### ISSUE THREAD

**Issue by lelodu87** [Tachyonite/Pawnmorpher#511]
**Describe the solution you'd like**
Compatibility with VBE so we can add some Pawnmorpher wallpapers to the starting menu.

**Additional context**
Very easy to do: https://i.imgur.com/qWnEDAx.png

**Comment by FxWolfxe** [comment]
was this fixed in the latest update?

**Comment by Zeracronius** [comment]
Yep
