### ISSUE TITLE
No pawns generated in Escaped Morphs scenario

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#514]
**Describe the bug**
When starting Escaped Morphs scenario and selecting inactive ideology, then no pawns are generated.

**To Reproduce**
1. Start Morph Escaped scenario
2. Select inactive ideology.

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/157541470-1bcccf97-f996-49b9-bf4d-91cb651dc6b1.png)
![billede](https://user-images.githubusercontent.com/64704191/157541500-b34236f9-21bc-41f5-a04e-6c56ed270861.png)

**Additional context**
https://discord.com/channels/603713246461165578/617156478150639682/951228529931059251

**Comment by lelodu87** [comment]
Issue confirmed, and the console is not happy...
[partial_log.txt](https://github.com/Tachyonite/Pawnmorpher/files/8318145/partial_log.txt)
