### ISSUE TITLE
Incorrect notification message with intelli-boost

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#517]
**Describe the bug**
When former human is taking intelliboost pills and pass a sapience threshold (25, 50 or 75 %) by going up, the letter say sapience has dropped and is not considered full colonist.

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/951964528457969784

**Comment by lelodu87** [comment]
Issue confirmed, and it is not related to intelli-boost: even through console, this error happens whenever we rise sapience level above 25%.
