### ISSUE TITLE
Hazsilk behaves differently between Morphs and Humans

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#520]
**Describe the bug**
Hazsilk seem to protect humans against mutanite mutations and yet doesn't protect morphs.

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/158694793-d2d6067c-8990-4b21-a454-8b08ca286ff4.png)
![billede](https://user-images.githubusercontent.com/64704191/158694498-01853069-be22-4cf5-87b8-93c9856006a7.png)
![billede](https://user-images.githubusercontent.com/64704191/158694589-811976a7-799f-4d88-970a-d2ab19854693.png)
![billede](https://user-images.githubusercontent.com/64704191/158694605-93ee6a9a-c905-4fec-9376-ceb19d81a42b.png)
![billede](https://user-images.githubusercontent.com/64704191/158694610-719edb74-3743-48ea-880d-ac26f5f4b737.png)

**Additional context**
https://discord.com/channels/603713246461165578/685319382079242274/953624382083829790

**Comment by lelodu87** [comment]
Did not manage to replicate that issue. My sheepmorph did not get mutated.

However, hazsilk behaviour is fishy. Chaomorph partial (x1) or Mutagenic Buildup appear for a tick, and then disappear. Perhaps the issue is related to that?

**Comment by FxWolfxe** [comment]
this might be specific to mutanite. that is handled differently then mutagenic fallout. still a bug though

**Comment by lelodu87** [comment]
> this might be specific to mutanite. that is handled differently then mutagenic fallout. still a bug though

Had the same ticking issue with slurry puddle.

**Comment by Zeracronius** [comment]
Ticking issue is found and expected. However i think this issue may be related to mutation affinity increasing mutation sensitivity, so even if stats show 0 from clothes it might not be.

Ticking issue is that hazsilk reduces mutation sensitivity, and the mutation hediff removed themselves if mutation sensitivity is 0.
However at least mutanite doesnt check for that before adding mutation, thus it gets added and immediately removed.

So there is potentially 2 things here, mutanite needs to check sensitivity when adding mutations, and we may need to rethink how mutation affinity works.

**Comment by Zeracronius** [comment]
Some testing shows that I remembered incorrectly about Mutation Affinity, and that is completely unrelated to any of this.

As it stands, the current issue here with hediff appearing and then instantly vanishing, the 'ticking issue' is down to Mutonite not checking if pawn has 0 mutation sensitivity, adding the hediff, which then promptly ask rimworld to remove it because pawn has 0 sensitivity.
This in itself is not an issue, however mutation hediffs removing themselves on 0 mutation sensitivity is an issue when hazsilk reduces mutation sensitivity. This means that a hazsilk suit will make a pawn completely immune to any existing mutation hediffs and _all_ new ones. Be that from Mutonite, Ingesting mutagenic eggs or milk, or even injector. Putting on a full hazsilk would instantly remove all of them. Which means it becomes a _much_ better option than stabilizers. Especially since it isn't consumed and you barely need to have it equipped.

I think we need a separation between sensitivity to adding new hediffs from external sources like weapons, mutonite and fallout vs mutating from existing hediffs and acquiring them from "internal" sources like injection or ingestion. And hazsilk should only protect against the former.

**Comment by Zeracronius** [comment]
Added mutation sensitivity check to mutanite.
