### ISSUE TITLE
Former feral pawns lose ideology.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#523]
**Describe the bug**
When pawns lose too much sapience and you then restore it, they are seemingly left without an ideology.

**To Reproduce**
1. Reduce former human sapience to feral.
2. Restore sapience.
3. Former human no longer has Ideology.

**Additional context**
https://steamcommunity.com/workshop/filedetails/discussion/1786466855/1643167006270947148/?ctp=54#c3186866558199400234

**Comment by lelodu87** [comment]
Confirmed. No messages in log.
It happens when the pawn reaches the "Feral" stage.

**Comment by Zeracronius** [comment]
This looks like it is by design.
