### ISSUE TITLE
Antigen not working as expected

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#541]
**Describe the bug**
Antigens only work when applied during the "transforming" phase and do nothing in the "changing" phase. They also don't cancel out accelerators.

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/963089547783208961

**Comment by lelodu87** [comment]
Issue confirmed. It seems it happens only when accelerator is combined with a transforming/changing phase.

**Comment by Zeracronius** [comment]
Works as intended.
