### ISSUE TITLE
Reverted Gordon lacks surname.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#542]
**Describe the bug**
Reverting the "A Ram Approaches" sheepmorph cauaes issues as the reverted pawn lacks a last name

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/963089547783208961

**Comment by lelodu87** [comment]
- Reverted Rams indeed do not have any last name. No troubles reverting though (still an issue later though).
- Seems to be a problem with the backstory: 

I have that though: Couldn't find exact match for backstory chef, or any close match. 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

Used SetFaction to change ewe 1 to same faction PlayerColony 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

- Some of them do not even have a proper noun (*blank blank*).
- Age does not seem to be properly checked: https://cdn.discordapp.com/attachments/603713246461165695/965542406885896222/unknown.png
