### ISSUE TITLE
[RPG style inventory] Former humans gear tab bugs out.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#544]
**Describe the bug**
Opening gear tab on former humans with RPG-style inventories causes issues.

**Mods Involved**
RPG style inventory.

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/963089547783208961

**Comment by lelodu87** [comment]
Seems fine, as former human don't have the same gear tab as human beings:
![image](https://user-images.githubusercontent.com/86140855/176871663-312f19b1-d5bb-4a46-8fd6-3d954f75ea0a.png)
