### ISSUE TITLE
[Androids] Androids are assigned needs.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#546]
**Describe the bug**
If you use Android mod with pawnmorpher, the droid's need tab will show things that they dont need (like sleeping) and it will constantly activate the "Need colonists bed" message although they can't even be assigned to a bed 

**Mods Involved**
Androids (https://steamcommunity.com/workshop/filedetails/?id=1541064015)

**Screenshot**
![billede](https://user-images.githubusercontent.com/64704191/174437395-9bd1caf0-014d-4ffd-8858-89c9a28f2121.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/917840582209060935

**Comment by Diakon5** [comment]
This appears to be a case of Harmony Patches conflicting. Loading Androids after Pawnmorpher eliminates the issue.
