### ISSUE TITLE
[MVCF/Vanilla Expanded Framework] Complains about tagging rifle

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#547]
**Describe the bug**
[MVCF] Found equipment with more than one ranged attack while that feature is not enabled. Enabling now. This is not recommend. Contact the author of Pawnmorpher and ask them to add a MVCF.ModDef.

**Mods Involved**
MVCF/Vanilla Expanded Framework

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/927932470500945980

**Comment by Diakon5** [comment]
Does not happen with just Vanilla Expanded Framework. Tested individually with a few Vanilla Expanded mods, with no results. Possible cause is a third party mod. Still investigating

**Comment by Zeracronius** [comment]
Error (warning shown as error) appears the first time a map is loaded after the game is started.

**Comment by Diakon5** [comment]
It isn't always triggered that way. Perhaps if there is any entity actively using MVCF which is more likely with increasing amount of mods.

Either way, triggered consistently by equipping the Tagging Rifle. Identified.

**Comment by Zeracronius** [comment]
As far as i can tell, it is basically that ranged verb framework complaining that there is a gun with multiple verbs and the framework isn't configured for multiple verbs. 
Except we don't even use that framework at all.

**Comment by Diakon5** [comment]
We do have a built-in integration to enable its features if need be. Added an extra line that causes the error to go Away. Shouldn't affect gameplay in any way, since the error enabled the feature anyway
