### ISSUE TITLE
Colonies Don't Load Right/Aren't Created

### ISSUE THREAD

**Issue by TheARate** [Tachyonite/Pawnmorpher#58]
(1.1) After updating to the latest dev build of Pawnmorpher, I set my modlist to Hugslib -> HAL2(Latest Steam Version) -> PW. I then tried to load an existing colony, which loaded without any pawns or animal pawns on the map. Strange.
I then tried to make a new colony, but after pulling up devmode, I ended up with errors like these:
![20200223152752_1](https://user-images.githubusercontent.com/53186958/75119794-2d91e880-5654-11ea-822c-29068a5bb41b.jpg)
It seems that Harmony and HAL2 are having issues with something. I'm going to post a portion of an error log that should contain these errors, excluding the mountain of "missing defs" and "null descriptions".
https://pastebin.com/jgJfMUps

Here is the entirety of an error log from one of these sessions:
https://gist.github.com/323edf2fd897e26931511d640630279b

Will update when necessary.

**Comment by FxWolfxe** [comment]
This can’t be reproduced reliably in the latest build for 1.1, closing for now.
