### ISSUE TITLE
Generated morphs lack certain mutations

### ISSUE THREAD

**Issue by BrennenCramer** [Tachyonite/Pawnmorpher#59]
**Describe the bug**
Morphs generated by the free morph start don't get all the mutations they are supposed to.

**To Reproduce**
1. Start up a new game with the free morphs start.
2. Check the hediffs that the generated morphs have (most noticeable on the monkey, who just get fur and their jaw)

**Expected behavior**
Morphs should be fully fleshed out and have more than one hediff per body slot.

**Screenshots**
![image](https://user-images.githubusercontent.com/48333768/75121496-65dff980-5649-11ea-846d-dfa1320f6a4b.png)

Just loaded with required framework mods.  No additional feature or QOL mods.

**Comment by FxWolfxe** [comment]
fixed in 3d5a2a4a73cfe7593a0d90996b76a9fc1acb01e9
