### ISSUE TITLE
I don't think the weapons work

### ISSUE THREAD

**Issue by USpook** [Tachyonite/Pawnmorpher#598]
So when i used the mutagenic grenades, the screen shook violently until i reloaded the save. When i used the mutagenic stun stick, it didn't hit anything but it leveled up the hitter to level 20 in seconds. I haven't tested any of the other weapons, but i feel they might also be broken

**Comment by Zeracronius** [comment]
Are you using Combat Expanded?

**Comment by lelodu87** [comment]
Nothing suspicious in base mod, for sure. This is very likely due to Combat Extended.
