### ISSUE TITLE
generated Pawn body part hediffs vanishing on save/load

### ISSUE THREAD

**Issue by TanyaSapien** [Tachyonite/Pawnmorpher#60]
**Describe the bug**

**To Reproduce**
1. Go to 'new game, create a gam'
2. Click on 'save game, exit to main menu, load game'

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/11e87cd80625d1f9ba359f5abb33e51a

**Expected behavior**
Morphed pawns should retain body parts, instead morph hediffs randomly vanish, apparently not saved correctly.

**Additional context**
Was observed on a pawn generated using Prepare Carefully.

**Comment by FxWolfxe** [comment]
this is a very weird log, the assembiles appear to be loaded multiple times. Also the only errors that seems like it could be related to the missing mutations is being caused by a patch from AllowTools and RimStory, can you reproduce this without those mods?

**Comment by FxWolfxe** [comment]
can't reproduce on the latest version of the mod, closing
