### ISSUE TITLE
Hellhound injector is available.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#601]
**Describe the bug**
Should hellhound injectors be available for purchase?

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/174436348-2157435a-22b0-4707-8f5a-3e1677758fc5.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/987200809722859530

**Comment by FxWolfxe** [comment]
hellhound injectors either shouldn't exist or be alot more expensive and harder to get then the other injectors. Generating them should be disabled in the MorphDef for now
