### ISSUE TITLE
[HAR] Body purist pawns of other races will freak out from race mutations.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#602]
**Describe the bug**
A body purist of another race will get a negative mood modifier from every mutation, even those related to their race.

Disable body purist mutation thought for other races? Maybe only for specifically the mutations related to their race?
Thought for missing race-specific mutation?

In this case it is an Orassan replacing Catmorph complaining about catmorph mutations

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/174436501-6def6fed-7741-487e-95e3-2389954b59e6.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/987101009698521168

**Comment by Diakon5** [comment]
Could be solved with a Def Extension perhaps? Don't believe there's a reliable way to auto-patch, only per-race patch.

Alternatively, there are overrides for morph races in mod settings. Apparently we can change the morph's race to an Alien race? It could hook off of that, but would require user input.
Both approaches could be used

**Comment by Zeracronius** [comment]
It is true we have the option to replace morphs with explicit races, and I added an options menu to allow users to do that recently.
The situation here is when a pawn is assigned the RaceMutationSettingsExtension which defines default race mutations, then body purists of that race still consider it as mutations rather than the norm.
What we want here is for body purists to not consider mutations assigned by this extension as "foreign". I assume we will need to locate where the decision on what does and doesn't trigger body purist and patch it to take this into consideration.

**Comment by Zeracronius** [comment]
Other mods can either manually assign RaceMutationSettingsExtension to a race specifically just for the mutations alone, or players can assign the race as an explicit morph race and it will be assigned automatically.
(This is required to prevent the pawns of this race from immediately being considered human after spawning.)

**Comment by Diakon5** [comment]
Then unless I misunderstand how the thoughts work, We just need to alter the thoughtworkers for the mutations.
