### ISSUE TITLE
Big morphs eating a lot cannot eat more at once than normal pawns.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#606]
**Describe the bug**
Large morphs need a lot of food, but they can only eat one meal at time. So they spend a lot of time getting snacks.
Even when using small food like pemmican they are limited to 20 at time.

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/987507293329428512

**Comment by FxWolfxe** [comment]
the amount eaten at a time should definitly scale with morph size
