### ISSUE TITLE
Former humans fleeing from combat

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#608]
**Describe the bug**
Former humans flee from combat regardless of threat response setting

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/989862534460887051

**Comment by lelodu87** [comment]
Confirmed. This is a bit more complex though:
- If they are drafted but not asked to attack, they will flee when they start to be attacked/bullets.
- If they are drafted and asked to attack (melee in my case), they'll not flee.
