### ISSUE TITLE
Feral pills don't always seem to trigger full TF during reeling.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#612]
**Describe the bug**
Feral pills don't always seem to trigger full TF during reeling.

**Additional context**
https://discord.com/channels/603713246461165578/685319382079242274/989178275983159326

**Comment by lelodu87** [comment]
Is there a way to make reeling easily? Waiting hours for reeling stage is long.

I tried with "changing", and I can confirm feral pills don't TF at this stage.

**Comment by Zeracronius** [comment]
This is caused by switching to new hediff system
