### ISSUE TITLE
Transparent body parts when facing north.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#613]
**Describe the bug**
Morph body parts become transparent when facing north.

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/176114680-62757585-c79b-4767-9167-5663ca72086f.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/991167440866258964

**Comment by lelodu87** [comment]
I did not manage to reproduce it, so it may be related to some morphs/mod.
