### ISSUE TITLE
Inspired recruitment does not affect former humans.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#615]
**Describe the bug**
Inspired recruitment does not affect former humans.

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/991711133499129886

**Comment by FxWolfxe** [comment]
oversight, this inspiration should work when recruiting sapient former humans

**Comment by Zeracronius** [comment]
In the Worker_FormerHumanRecruitAttempt.Interacted, as far as i can tell, it _only_ considers recruiting if target former human is a sapient guest. And in that case, Inspired recruiting is considered.
However, if it is a sapient former human in the "wild", it will still always be considered taming and it will only consider inspired taming in that case. However the message to users will be "Taming" or "Recruiting" depending on target sapience, even if it is a taming attempt.
