### ISSUE TITLE
Escape pod refugees/enemies always die on impact

### ISSUE THREAD

**Issue by lelodu87** [Tachyonite/Pawnmorpher#618]
**Describe the bug**
I have spawned escape pod events 11 times, each time the pawn died on impact due to their injuries. This is not normal. It happened in a normal game too (dev build).

**To Reproduce**
Just spawn an escape pod event and enjoy a free death!

**Additional context**
I am not certain, but I think it happened too with the "escape royal" quest that spawn at the beginning of a game.

**Comment by Zeracronius** [comment]
I just tested this in a fresh scenario, out of 10 events only 1 died on impact
