### ISSUE TITLE
Unable to control sapient former humans

### ISSUE THREAD

**Issue by Cpt-Dingus** [Tachyonite/Pawnmorpher#623]
As the title says, I cannot control/view the mood of former humans that are sapient. I am not sure whether this is intentional or not, as I get an error every time I attempt to get the former human to interact with anything.
![image](https://user-images.githubusercontent.com/100243410/177144300-d31b8d3f-e654-42b1-bcd4-037ebc29c0e2.png)

I just built the mod, it is the latest version.
As for an image of the bug (no mood but sapience is at 100%):
![image](https://user-images.githubusercontent.com/100243410/177144572-91868225-72f8-4f0a-9c6b-8189e1edffe3.png)

**Comment by Cpt-Dingus** [comment]
Sorry for the improper formatting, github didn't show the presets when trying to create new issue

**Comment by Cpt-Dingus** [comment]
Reopened

**Comment by Cpt-Dingus** [comment]
Accidentally closed.

**Comment by Zeracronius** [comment]
Please include actual log rather than just an image. I cannot read the entire error or the stack trace from the image and as such cannot do anything.

**Comment by Cpt-Dingus** [comment]
Hello, how would I go about doing that?

**Comment by Cpt-Dingus** [comment]
[Here you go](https://gist.github.com/HugsLibRecordKeeper/cba12b9107e88dba40b582dcfa4e645b)

**Comment by Zeracronius** [comment]
There is a lot of UI related error spam in the log, but I cannot see anything relating to PM. There is a failing transpiler patch related to IsRoped def, but as far as I can see, that is seemingly unrelated to the errors.

**Comment by Cpt-Dingus** [comment]
A notable PM error I found in it is this:
> Exception in Pawnmorph.ThinkNodes.ConditionalSapientAnimal TryIssueJobPackage: System.NullReferenceException: Object reference not set to an instance of an object
  at RimWorld.JobGiver_Work.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x0010a] in <3f8399aa16fa418f9dff5e3ec4ac6fc6>:0 
  at Verse.AI.ThinkNode_Priority.TryIssueJobPackage (Verse.Pawn pawn, Verse.AI.JobIssueParams jobParams) [0x00022] in <3f8399aa16fa418f9dff5e3ec4ac6fc6>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Comment by Cpt-Dingus** [comment]
This issue seems to have run cold, I have attempted to get a newer log and managed to get this: https://gist.github.com/8a37be31f56cb6864e6e3e7ff8535d6f

All of the AI exceptions happen only when I have a tf'ed pawn and try to interact with it.

**Comment by Zeracronius** [comment]
It hadn't gone cold, but i am the only one maintaining this mod and I was working on some other issues at the time, and then rimworld 1.4 and Biotech hit and I've been fighting to get it to run even somewhat stable since.
And now I can start looking into other issues again.

The last log you pasted seem to have multiple patching issues seemingly related to outdated rimworld version.
MVCF and Pawnmorpher both throw error during patching.
This will lead to completely unpredictable issues and may well be related to all the other problems.

**Comment by Cpt-Dingus** [comment]
Sorry, this issue is old as balls and I don't seem to be experiencing it anymore on newer releases, I can't repro it.
