### ISSUE TITLE
Build.ps1 uses wrong directory for MSBuild.exe, doesn't work

### ISSUE THREAD

**Issue by Cpt-Dingus** [Tachyonite/Pawnmorpher#624]
**Describe the bug**
Attempting to build the mod won't work with visual studio 2022, as it uses the wrong file path for MSBuild.exe

**To Reproduce**
1. Download code as zip
2. Run build.ps1 in powershell
3. See error

**Error Log**
[Powershell log](https://pastebin.com/MJisZzVw)

**Expected behavior**
The mod will build properly.

**Screenshots**
N/A

**Additional context**
Changing lines 36 and 45 of build.ps1 to the following makes it work:
`."C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"  "Source/Pawnmorphs/Pawnmorph.sln" /t:restore`
`."C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"  "Source/Pawnmorphs/Pawnmorph.sln" /t:Rebuild /p:Configuration=$buildType /p:Platform="any cpu"`

**Comment by Zeracronius** [comment]
Powershell script is completely depending on what version of where your msbuild is installed.

If you have visual studio installed, I suggest using that to compile the solution instead of the powershell script.
