### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by Niveon** [Tachyonite/Pawnmorpher#625]
**Describe the bug**
For Capybaramorph ears, it says "PWAN" where it's meant to say "PAWN", resulting in some dead code rather than the pawn's name being displayed.
For Thrumbomorphs, the Thrumbofur is called Thumbofur

**To Reproduce**
Just have the Capybara ears or Thrumbofur present on the character to see the typos.

**Error Log**
N/A

**Expected behavior**
For Capybara ears it wouldn't give a dead code prompt, for the Thrumbofur it'd just be spelled correctly.

**Screenshots**
https://i.imgur.com/kBJUlsD.png (for Thumbofur)

**Additional context**
N/A

**Comment by Zeracronius** [comment]
Already fixed in dev and available in latest test version on discord.
