### ISSUE TITLE
Turtle beak missing.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#628]
**Describe the bug**
Turtle beak is missing.

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/177579115-e09f8864-69eb-4b7d-ba86-9f2b6a47572d.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/994087822799679600

**Comment by lelodu87** [comment]
With a clean Pawnmorpher, I've no issues with an adapted beak. It appears correctly.
However, I used make morph command, so may be another glitch. But for sure, the texture path is correct.
