### ISSUE TITLE
Canonical/Game balance stats toggle

### ISSUE THREAD

**Issue by yoopgim** [Tachyonite/Pawnmorpher#629]
I overall feel like a whole bunch of the memories are split between canonically accurate mood difference(makes sense depending on description and traits) and balanced for gameplay (stats that make sence for the balance of the gameplay), I have also noticed that there are 2 sections of the fanbase for rimworld (no not the hats vs survivors thing): game vs story generator. 

Because of those two things, i have come up with an idea for the mod's memory stats: An option in the settings to switch between canon and balanced, most likely default on canonical (b/c the creator of rimworld advertises the game as a story generator)

I *think* that it should be possible considering that cherrypicker exists, but im not entirely sure. 

thanks for making and updating this mod  

u da bes

P.S. 
when i first played the mod (which is the one i was looking forward to the most when i bought rimworld) i noticed that the guinea pig was the only vanilla animal that didnt have a morph, it stumped me a bit lol, so thanks for adding the morph!

**Comment by lelodu87** [comment]
While this might be giving more immersion, this is way too costly (need a lot more of text, some patches, etc.) for very minimal gains in immersion. Balance is something important for us. Sadly, we don't have enough time to do everything we want, and have to select suggestions.

If you have new suggestions, prefer if possible Discord or Steam to post your suggestions. Thank you!
