### ISSUE TITLE
Pawns transform and revert with gear.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#638]
**Describe the bug**
A pawn can turn into a former human and back and retain all their gear.

**Additional context**
https://discord.com/channels/603713246461165578/603713246461165695/995397773220393011

**Comment by lelodu87** [comment]
Confirmed: I managed to do that:

1- My pawn was wearing a prestige cataphract armor, synthread clothes and a mutarifle.
2- I used a syringue on it (turtoise).
3- Force transformation on it with a commande. It didn't drop anything, but 4 morphsilk (created on TF, supposed to compensate clothing?).
4- When reverted, it got everything back on them.

No specific log for the issue.
