### ISSUE TITLE
Mutagenic chambers without modulators always produce the same animal

### ISSUE THREAD

**Issue by RadHazard** [Tachyonite/Pawnmorpher#64]
**Describe the bug**
Mutagenic chambers always seem to produce the same animal when not given a modulator.  The animal is different for every chamber but each chamber consistently produces the same animal (e.g. I had one chamber that transformed everyone placed into it into a snowhare, and another that transformed everyone into yaks)

**To Reproduce**
1. Build a mutagenic chamber
2. Mutate several totally voluntary test subjects in said chamber
3. Observe all test subjects come out as the same species

**Expected behavior**
Unmodulated chambers produce random animals rather than the same one every time.

**Comment by mc-oofy** [comment]
thats probably not a bug

**Comment by FxWolfxe** [comment]
old chambers and modulaters were removed in 1.10.0
