### ISSUE TITLE
Launching without the Vanilla Expanded Framework causes a black screen

### ISSUE THREAD

**Issue by Turnovus** [Tachyonite/Pawnmorpher#640]
**Describe the bug**
The Vanilla Expanded Framework is not listed as a dependency on either the Steam Workshop or the mod's about.xml. However, attempting to launch the game without VEF causes root-level errors that result in a black screen.

**To Reproduce**
I enabled all of the content listed by Pawnmorpher's metadata, and nothing more. If I launch the game without VEF, I get a black screen. But if I launch with VEF enabled, then the main menu loads normally.

My load order is: Harmony, Core, HugsLib, HAR, Vanilla Expanded Framework (when enabled), Pawnmorpher

**Error Log**
I've attached the log file from the AppData directory, as submitting it through HugsLib is physically impossible. A lot of the log consists of the same few errors repeated many times.
[Player.log.txt](https://github.com/Tachyonite/Pawnmorpher/files/9087076/Player.log.txt)

The first stack trace, in particular, really stands out. It seems as though the issue is being caused by the game trying to read an invalid XML file:
```
Exception reading Addon_GasTrapsAndShells.xml as XML: System.Xml.XmlException: Root element is missing.
  at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x00027] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0035d] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlTextReaderImpl.Read () [0x0008c] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlLoader.Load (System.Xml.XmlDocument doc, System.Xml.XmlReader reader, System.Boolean preserveWhitespace) [0x000a6] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at System.Xml.XmlDocument.Load (System.Xml.XmlReader reader) [0x0002e] in <0f9699188f0c414ea6fb5557f5c16d15>:0 
  at Verse.LoadableXmlAsset..ctor (System.String name, System.String fullFolderPath, System.String contents) [0x00049] in <81af9f8a18324e17b286924a43555a7c>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
```

**Comment by Zeracronius** [comment]
VEF is not required by PM itself, but multiple mods with integrations and sub mods does require it, like Monster Hunter Rim or Insectoids.

Do you have any other mods in your mod list than listed under load order?

**Comment by Turnovus** [comment]
> Do you have any other mods in your mod list than listed under load order?

No, I made sure to test it while running only the mods required by Pawnmorpher itself. I also tried re-subscribing through the Steam Workshop.

**Comment by Zeracronius** [comment]
I cannot reproduce this issue. Can you provide a hugslib log for when you have VEF enabled and the game loads successfully?

**Comment by Turnovus** [comment]
While I was getting the log you requested, I tried reinstalling the mod one more time just to be certain, this time checking that the mod's folder was actually removed from my workshop directory. Now everything appears to be working fine. I can only assume that my files either became damaged at some point, or were not fully updated by Steam.

Here's the log anyways, in case it helps: https://gist.github.com/HugsLibRecordKeeper/5465e402159a80504d0305050b6b79bd
Notice around line 900 it starts throwing errors about missing body anchors. These errors have also gone away after reinstalling.

Sorry for any inconvenience this has caused.
