### ISSUE TITLE
Stabilized pawns throw an error in mutagenic chambers

### ISSUE THREAD

**Issue by RadHazard** [Tachyonite/Pawnmorpher#66]
**Describe the bug**
If you place a pawn with an active Mutagen Stabilized hediff in a mutagenic chamber, the progress will tick to 100%, then throw an error and reset to 0.  The pawn remains in the chamber but can be ejected manually.

**To Reproduce**
1. Give a pawn stabilizer pills
2. Place the pawn in a mutagenic chamber
3. Observe that an error is logged when progress reaches 100%

**Error Log**
https://gist.github.com/c24b6db0257ce2b089a5b85ee4d211a5

**Expected behavior**
Stabilized pawns are either ejected untransformed or transformed, depending on what you all think is the correct behavior.  No error is thrown.

**Comment by FxWolfxe** [comment]
old chambers were removed in 1.10.0, this should be fixed for the new ones
