### ISSUE TITLE
More than a few races breaks "morph Replacements" 

### ISSUE THREAD

**Issue by Thatfoxyoudontknow** [Tachyonite/Pawnmorpher#676]
**Describe the bug**

**To Reproduce**
0. have quite a few race mods (like a total of almost 50 total races added)
1. Go to the replacements menu
2. Click on the blank bar
3. See error

**Error Log**
Exception filling window for Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements: System.NullReferenceException: Object reference not set to an instance of an object
  at Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements.DoWindowContents (UnityEngine.Rect inRect) [0x00326] in <84785d16db8a4f7b82419fa077f4cbdb>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x001d3] in <81af9f8a18324e17b286924a43555a7c>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

 **and**
 
 Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Widgets:EnsureMousePositionStackEmpty ()
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

**Expected behavior**
a small drop down bar appears with a list of races, you click one and it replaces the blank bar.
(never actually selected a race but I saw it when I only had 2 races installed)
**Screenshots**

**Additional context**
I have added nothing but race mods since it stopped working, it is not be any of the other mods as I loaded up the game with an empty list + better loading, mod manager, the race mods(and their dependencies, the only one of which isn't also one of pawnmorpher's was working fine before the addition of too many mods) and pawnmorpher.

**Comment by Zeracronius** [comment]
The number of mods shouldn't matter.
Did you add any non-har  (humanoid alien races) based species? Can you link one of them if so?
It is quite possible that that is what breaks it.

**Comment by Thatfoxyoudontknow** [comment]
I have loaded all of them at once and have gotten the same bug (aside from 2 I found no morph for), same error, will try a few at a time to confirm its not just one mod doing this.

**Comment by Zeracronius** [comment]
If you still get the error with the test version, can you plop a new log?

**Comment by Thatfoxyoudontknow** [comment]
**first.**
Exception filling window for Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements: System.NullReferenceException: Object reference not set to an instance of an object
  at Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements.<DoWindowContents>b__15_0 (Pawnmorph.MorphDef morph, Verse.Listing_Standard listing) [0x00170] in <c101f150058446fe965f0491344852fd>:0 
  at Pawnmorph.User_Interface.FilterListBox`1[T].Draw (UnityEngine.Rect inRect, System.Single x, System.Single y, System.Single height, System.Action`2[T1,T2] callback) [0x0012d] in <c101f150058446fe965f0491344852fd>:0 
  at Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements.DoWindowContents (UnityEngine.Rect inRect) [0x000b9] in <c101f150058446fe965f0491344852fd>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x001d3] in <81af9f8a18324e17b286924a43555a7c>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate **(UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)** `

**second.** 
Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Widgets:EnsureMousePositionStackEmpty ()
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

**Third.**
Exception filling window for Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements: System.NullReferenceException: Object reference not set to an instance of an object
  at Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements.<DoWindowContents>b__15_0 (Pawnmorph.MorphDef morph, Verse.Listing_Standard listing) [0x00170] in <c101f150058446fe965f0491344852fd>:0 
  at Pawnmorph.User_Interface.FilterListBox`1[T].Draw (UnityEngine.Rect inRect, System.Single x, System.Single y, System.Single height, System.Action`2[T1,T2] callback) [0x0012d] in <c101f150058446fe965f0491344852fd>:0 
  at Pawnmorph.User_Interface.Settings.Dialog_RaceReplacements.DoWindowContents (UnityEngine.Rect inRect) [0x000b9] in <c101f150058446fe965f0491344852fd>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x001d3] in <81af9f8a18324e17b286924a43555a7c>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)

**Fourth.** 
Mouse position stack is not empty. There were more calls to BeginScrollView than EndScrollView. Fixing.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.Widgets:EnsureMousePositionStackEmpty ()
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()

**Comment by Zeracronius** [comment]
Made a new version to hopefully sort it. Your new logs based on current test version helped narrow it down a lot, but it is still not detailed enough to be specific. 
That is why this is still only a best guess on my part.
[Pawnmorpher-Debug_Issue676_ReplacementOptions_08-22.zip](https://github.com/Tachyonite/Pawnmorpher/files/9397145/Pawnmorpher-Debug_Issue676_ReplacementOptions_08-22.zip)

I added some checks on showing source mod, so you might have some options showing "()". 
Do let me know if that is the case and if it works!

**Comment by Thatfoxyoudontknow** [comment]
ok it seemed to be just one race, though when i had tried this process on the older version of pawnmorpher it stopped working after about 25~ races were added, or something in this version is just compatible with over half the noncompatible one from before (so far the problem mods were ''Xenohumans - Anthromorphes'' , that the only one out 63)

**Comment by Thatfoxyoudontknow** [comment]
I will try the new test version see how it brings up error logs, reporting back with results

**Comment by Thatfoxyoudontknow** [comment]
<img width="296" alt="bugsquashed" src="https://user-images.githubusercontent.com/111541835/186018329-b34b2222-2568-4719-ad92-92e04de9d9d0.PNG">
it worked!

everything else loads normally too!

**Comment by Zeracronius** [comment]
Huh, so that was the issue. Glad to hear it works!

Don't worry about the issue, it will be closed when the fix goes live on the workshop.

**Comment by Thatfoxyoudontknow** [comment]
also a new morph that I don't remember seeing appeared
"shark morph"

**Comment by Zeracronius** [comment]
I believe that is from MHR
