### ISSUE TITLE
[Android Tiers] T2 android tiers with udder.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#678]
**Describe the bug**
"Speaking of cow, android tiers mod strikes again - i have a t2 android that somehow has grown an udder"

**Mods Involved**
Android Tiers

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/1010649809960587284

**Comment by Diakon5** [comment]
Android Tiers Androids appear properly patched to be mutation proof. Only potential cause i have found was Android Tiers:Gynoids Reborn, which performs a full def overwrite(not a patch. It just defines the same def again with its changes, and I do not know how that doesn't cause an error).
Needs further investigation
