### ISSUE TITLE
Double master moodlet.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#679]
**Describe the bug**
Pet master moodlet appears twice.

**Screenshots**
![billede](https://user-images.githubusercontent.com/64704191/185765468-81e6a712-0671-4e89-9b9c-684bdd94cd15.png)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/1010639081820139610

**Comment by Diakon5** [comment]
Related: #643
