### ISSUE TITLE
Can't Eat Meat (maybe others)

### ISSUE THREAD

**Issue by ClayDragon09** [Tachyonite/Pawnmorpher#694]
they grab the food and do the process but at the end the food just drops to the ground and they dont eat it, I have tried rimpy, which made it worse, I have a lot of mods but i have had this problem before with not even one mod the same and I really don't wanna spend 2 hours finding exactly witch mod(s) caused it so i ask that someone help

**To Reproduce**
anytime my pawns eat

LOG:
https://gist.github.com/84352ef1d0591981cb69c55a04d0fe2f

**Comment by Zeracronius** [comment]
Unfortunately it is impossible to say anything conclusively from the provided log.
You will need to at the very least supply as much specific information as possible, like details on pawn, race, involved mods (like if the pawn is from a mod or using parts from a mod etc), stats, morph status, health status (like mutations) and so on.

Something is causing a sapience check to fail which shouldn't be possible.
Since there is no obvious cause then we'll need to aim broad.

**Comment by ClayDragon09** [comment]
it is a NEKO from Orrassans which is why it has cat ears and tail however it is considered a mutation, but it is not

**Comment by ClayDragon09** [comment]
i could send a couple of screenshots if that isnat enough

**Comment by ClayDragon09** [comment]
it can also eat certain things, like Bearberrys from a mod i dont know

**Comment by ClayDragon09** [comment]
im not sure if this is a differnt thing or the same but ill post it just in casehttps://gist.github.com/HugsLibRecordKeeper/318d0f6ab1f7aa8f2a1c38e80bbbe72b

**Comment by Zeracronius** [comment]
Specifically from the looks of it, pawn is trying to get a memory on ingesting meat and then trying to check pawnmorpher sapience but for whatever reason, the pawn is null.

What traits does the pawn(s) in question have?
Do you have your ideology (if any) have something related to eating, meat or vegetarian?
Vanilla Expanded traits is mentioned in the log, but I so far can't tell if it is involved or not.

**Comment by ClayDragon09** [comment]
i have all the current vannila expanded mods... i do not have an ideoligy realted to conumtion other than being fine with insect, human, and alien meat. the pawn in question is(i should've metioned this) all of the irregardless, if you want a trait lkiks i can send one but ime afraid it would ber renduntet howvwe i will send a screenshot of my ideoligon

**Comment by ClayDragon09** [comment]
![image](https://user-images.githubusercontent.com/113483937/190503831-dc50a45f-9e7a-4d96-bc71-623415a8b7b9.png)
 
![image](https://user-images.githubusercontent.com/113483937/190503946-42ca3684-08e0-4cf2-a10c-2d806236dda9.png)

![image](https://user-images.githubusercontent.com/113483937/190504043-acb8962f-254d-4539-8424-23f360c4915d.png)

**Comment by Zeracronius** [comment]
I was asking for the traits of the pawns failing at eating. As it may or may not be related.

**Comment by ClayDragon09** [comment]
they all have different traits
