### ISSUE TITLE
[Feature] Mutagenic defenses

### ISSUE THREAD

**Issue by RadHazard** [Tachyonite/Pawnmorpher#70]
A collection of ideas for possible mutagenic defenses

**Mutarifle turret**
A stationary turret like the miniturret that fires the same projectiles as the mutarifle.  Refuelled with slurry

**Mutagrenade turret**
A turret that launches grenades similar to the mutagrenades.  Short ranged and with a forced miss chance.  Refuelled with slurry

**Slurry mister**
Short range turret that sprays a fine mist of mutagenic slurry.  Larger AOE and faster fire rate than the mutagrenade turret, but gives less buildup and has an even shorter range.

Could be implemented as a turret that fires projectiles that merely look and sound like gas puffs, or possibly through integration with another gas field mod.

**Comment by FxWolfxe** [comment]
this was split off into it's own mod
