### ISSUE TITLE
[Zombieland] Massive lag

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#716]
**Describe the bug**
PM checks for mutation tracker on all zombies spawned which leads to a lot of lag.

**Mods Involved**
Zombieland

**Error Log**
> pawn Michael 'Mike' Willey does not have a mutation tracker comp
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
Pawnmorph.DebugUtils.DebugLogUtils:WarningOnce (string,int)
Pawnmorph.MutationUtilities:GetMutationTracker (Verse.Pawn,bool)
(wrapper dynamic-method) EBF.Patches.Unification.Pawnmorpher.Mixed_Pawnmorpher_GetPartMaxHealth:EBF.Patches.Unification.Pawnmorpher.Mixed_Pawnmorpher_GetPartMaxHealth.GetPartMaxHealthDueToPawnmorpher_Patch0 (Verse.BodyPartRecord,Verse.Pawn)
EBF.Util.CommunityUnificationUtil:GetPartMaxHealthFromPawnmorpher (Verse.BodyPartRecord,Verse.Pawn)
EBF.EBFEndpoints:GetMaxHealthWithEBF (Verse.BodyPartRecord,Verse.Pawn,bool)
EBF.Patches.Unification.Pawnmorpher.Mixed_Pawnmorpher_GetPartMaxHealth:ManuallyPatchTheMethod (single&,Verse.BodyPartRecord,Verse.Pawn)
(wrapper dynamic-method) Pawnmorph.BodyUtilities:Pawnmorph.BodyUtilities.GetPartMaxHealth_Patch2 (Verse.BodyPartRecord,Verse.Pawn)
(wrapper dynamic-method) Verse.HediffSet:Verse.HediffSet.GetPartHealth_Patch0 (Verse.HediffSet,Verse.BodyPartRecord)
(wrapper dynamic-method) Verse.PawnCapacityUtility:Verse.PawnCapacityUtility.CalculatePartEfficiency_Patch1 (Verse.HediffSet,Verse.BodyPartRecord,bool,System.Collections.Generic.List1<Verse.PawnCapacityUtility/CapacityImpactor>)
(wrapper dynamic-method) Verse.PawnCapacityUtility:Verse.PawnCapacityUtility.CalculateTagEfficiency_Patch0 (Verse.HediffSet,Verse.BodyPartTagDef,single,Verse.FloatRange,System.Collections.Generic.List1<Verse.PawnCapacityUtility/CapacityImpactor>,single)
(wrapper dynamic-method) RimWorld.PawnCapacityWorker_Sight:RimWorld.PawnCapacityWorker_Sight.CalculateCapacityLevel_Patch1 (RimWorld.PawnCapacityWorker_Sight,Verse.HediffSet,System.Collections.Generic.List1<Verse.PawnCapacityUtility/CapacityImpactor>)
(wrapper dynamic-method) Verse.PawnCapacityUtility:Verse.PawnCapacityUtility.CalculateCapacityLevel_Patch4 (Verse.HediffSet,Verse.PawnCapacityDef,System.Collections.Generic.List1<Verse.PawnCapacityUtility/CapacityImpactor>,bool)
(wrapper dynamic-method) Verse.PawnCapacitiesHandler:Verse.PawnCapacitiesHandler.GetLevel_Patch0 (Verse.PawnCapacitiesHandler,Verse.PawnCapacityDef)
RimWorldRealFoW.CompFieldOfViewWatcher:CalcPawnSightRange (Verse.IntVec3,bool,bool)
RimWorldRealFoW.CompFieldOfViewWatcher:LivePawnCalculateFov (Verse.IntVec3,single,bool,RimWorld.Faction)
RimWorldRealFoW.CompFieldOfViewWatcher:updateFoV (bool)
RimWorldRealFoW.CompFieldOfViewWatcher:PostSpawnSetup (bool)
RimWorldRealFoW.CompMainComponent:PostSpawnSetup (bool)
(wrapper dynamic-method) Verse.ThingWithComps:Verse.ThingWithComps.SpawnSetup_Patch3 (Verse.ThingWithComps,Verse.Map,bool)
(wrapper dynamic-method) Verse.Pawn:Verse.Pawn.SpawnSetup_Patch11 (Verse.Pawn,Verse.Map,bool)
(wrapper dynamic-method) Verse.GenSpawn:Verse.GenSpawn.Spawn_Patch6 (Verse.Thing,Verse.IntVec3,Verse.Map,Verse.Rot4,Verse.WipeMode,bool)
(wrapper dynamic-method) Verse.GenPlace:Verse.GenPlace.TryPlaceDirect_Patch2 (Verse.Thing,Verse.IntVec3,Verse.Rot4,Verse.Map,Verse.Thing&,System.Action2<Verse.Thing, int>)
Verse.GenPlace:TryPlaceThing (Verse.Thing,Verse.IntVec3,Verse.Map,Verse.ThingPlaceMode,Verse.Thing&,System.Action2<Verse.Thing, int>,System.Predicate1<Verse.IntVec3>,Verse.Rot4)
Verse.GenPlace:TryPlaceThing (Verse.Thing,Verse.IntVec3,Verse.Map,Verse.ThingPlaceMode,System.Action2<Verse.Thing, int>,System.Predicate`1<Verse.IntVec3>,Verse.Rot4)
ZombieLand.ZombieGenerator/<>cDisplayClass14_0:<SpawnZombieIterativ>b13 ()
ZombieLand.ZombieGenerator:RunWithFailureCheck (System.Exception&,System.Action)
ZombieLand.ZombieGenerator/<SpawnZombieIterativ>d__14:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/1025212310463201280

**Comment by Diakon5** [comment]
Zombies are Humanlike, but are not selectable and feature many other removed components. Perhaps we can restrict the mutagen vulnerability to AlienRace.ThingDef_AlienRace Humanlikes only?

**Comment by Diakon5** [comment]
Pushed a PR that reportedly fixes it
