### ISSUE TITLE
Gene Effects are Ignored when Pawnmorpher Enabled

### ISSUE THREAD

**Issue by raistlain** [Tachyonite/Pawnmorpher#750]
**Describe the bug**
When Pawnmorpher is enabled, whether near the top of the load list or the bottom, genes affecting attributes (such as manipulation and sight) are ignored. 

**To Reproduce**
1. Enable Pawnmorpher and dependencies
2. Start new game as Crashlanded
3. Set one pawn to spawn as Geniekin
4. Wait for cryopod effect to expire (4h) if present
5. See that manipulation is stuck at 100% despite supposed to be in 110% due to "Elongated Fingers"

**Error Log**
If applicable the log of the error

**Expected behavior**
Genes from Biotech and/or mods should affect attributes such as manipulation.

**Screenshots**

**Additional context**
Confirmed present with ONLY Pawnmorpher and its direct dependencies. Also confirmed alongside many other mods.

**Comment by Zeracronius** [comment]
Have you tried with just HAR and no PM? Humanoid Alien Races is still actively working on biotech support.

**Comment by raistlain** [comment]
Tested again with only HAR. Problem does not occur. Problem only seems to appear when Pawnmorpher is active

**Comment by raistlain** [comment]
Without Pawnmorpher:
<img width="625" alt="image" src="https://user-images.githubusercontent.com/44714176/209032669-a6f14dfc-526f-4b72-a715-7a6ec2b1ee80.png">

With Pawnmorpher:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/44714176/209033421-f1bf7c20-24e3-4857-a439-ce29a3edbb93.png">
