### ISSUE TITLE
Experimental

### ISSUE THREAD

**Issue by ShigariBoi** [Tachyonite/Pawnmorpher#79]
**Describe the bug**
Deletes all the morphs I had in the previous build. The other stuff I had from PM, like mutagens, stayed though.

**To Reproduce**
1. Install latest test build
2. Launch a game with morphs

**Error Log**
Could not resolve reference to object with loadID Thing_HuskyMorphRace_Implied903357 of type Verse.Pawn. Was it compressed away, destroyed, had no ID number, or not saved/loaded right? curParent=chitchat: Espresso->null curPathRelToParent=
Verse.Log:Warning(String, Boolean)
Verse.LoadedObjectDirectory:ObjectWithLoadID(String)
Verse.CrossRefHandler:TakeResolvedRef(String, IExposable)
Verse.CrossRefHandler:TakeResolvedRef(String)
Verse.Scribe_References:Look(Pawn&, String, Boolean)
Verse.PlayLogEntry_Interaction:ExposeData()
Verse.CrossRefHandler:ResolveAllCrossReferences()
Verse.ScribeLoader:FinalizeLoading()
Verse.Game:LoadGame()
Verse.SavedGameLoaderNow:LoadGameFromSaveFileNow(String)
Verse.<>c:<Start>b__1_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Expected behavior**
Load the game, and still have my morphs.

**Screenshots**
![image](https://user-images.githubusercontent.com/61603850/75805368-fe7d2480-5d81-11ea-88fa-396efa66e9c0.png)

**Additional context**
  malteschulze.rimmsassemble
    brrainz.harmony
    ludeon.rimworld
    ludeon.rimworld.royalty
    unlimitedhugs.hugslib
    jecrell.jecstools
    erdelf.humanoidalienraces
    walkingproblem.aaf
    haplo.miscellaneous.core
    arandomkiwi.rimsaves
    neptimus7.progressrenderer
    madeline.modmismatchformatter
    sarg.smartspeed
    cabbage.rimcities
    loconeko73.roadsoftherim
    nilchei.powerfulfactionbases
    woolstrand.realruins.mod
    vanya.tools.blightedalert
    tammybee.predatorhuntalert
    zylle.extraalerts
    krafs.levelup
    sandy.rpgstyleinventory
    notfood.researchpal
    erdelf.showmoddesignators
    pelador.brrrandphew
    mlie.wehadatrader
    voult.betterpawncontrol
    dubwise.dubsbreakmod
    uuugggg.replacestuff
    saakra.factioncolonies
    frozensnowfox.filthvanisheswithrainandtime
    ogliss.ykara.harvesteverything
    smuffle.harvestorganspostmortem
    jaxe.boommod
    jkluch.haultostack
    agentblac.makepawnsprisoners
    jaxe.bubbles
    paradies.invisiblehats
    hatti.qualitybuilder
    crlsniper.metaldoesntburn
    hobtook.mortaraccuracy
    ebonjaeger.repowerreborn
    frozensnowfox.nodefaultshelfstorage
    supes.selectedreconnector
    ogre.ogrestack
    extracting.organs
    tradingspot.kv.rw
    slaves.rules
    falconne.heatmap
    brrainz.achtung
    roolo.giddyupcore
    roolo.giddyupcaravan
    mehni.pickupandhaul
    petetimessix.simplesidearms
    tammybee.whereismyweapon
    avilmask.commonsense
    pathavoid.kv.rw
    falconne.aff
    hoodie.whileyoureup
    vanya.tools.bulkcarrier
    uuugggg.sharetheload
    uuugggg.miningpriority
    uuugggg.smartmedicine
    uuugggg.usebedrolls
    brrainz.justignoremepassing
    lf.nomorecatatonia
    ryflamer.misc.drawabead
    ryder.satisfiedstorage
    tammybee.cutplantsbeforebuilding
    devdisigdu.bulk.components
    murmur.enemyselfpreservation
    murmur.factionresources
    vanillaexpanded.vee
    frozensnowfox.moreworldquests
    albion.goexplore
    solaris.bioreactor
    elstrages.cyberneticstorm
    jaxxa.ed.embrasures
    cocaine.electricstonecuttingtable
    ykara.epoe
    abraxas.mserevived
    rah.rbse
    com.rimworld.nales.expandedrims
    ratys.madskills
    gt.sam.glittertech
    teok25.archotechexpanded
    biscuit.archotechplus.10
    frozensnowfox.advancedbionicsexpansion
    spoonshortage.adogsaidanimalprosthetics
    chjees.androids
    fluffy.pharmacist
    oblitus.animalslogic
    sineswiper.factionblender
    sineswiper.xenobionicpatcher
    arandomkiwi.raidsforme
    diddily.portalgun
    ogliss.thewhitecrayon.quarry
    joethetech.marinearmormaterials
    lingluo.maidproject
    dninemfive.advancedshieldbelts
    automatic.rimlaser
    adarafirecaster.buyablequestrewards
    proxyer.makeableartifacts
    knight.medicalivs
    itchyflea.medicaltraining
    haplo.miscellaneous.training
    bichang.moresculpture
    gt.sam.tilledsoil
    vanillaexpanded.vfecore
    vanillaexpanded.vfesecurity
    dismarzero.vgp.vgpvegetablegarden
    dismarzero.vgp.vgpgardentools
    dismarzero.vgp.vgpgardenresources
    dismarzero.vgp.vgpgardenmedicine
    dismarzero.vgp.vgpgardengourmet
    dismarzero.vgp.vgpgardenfabrics
    dismarzero.vgp.vgpgardendrinks
    ratys.rtsolarflareshield
    neceros.fuseplus
    pelador.fireextinguisher
    pelador.firewarden
    murmur.walllight
    pelador.ssfetempfix
    rimfridge.kv.rw
    stolij.morebatteries
    doctorvangogh.miningshaft
    ling.thelowcooler
    siscos.adv.power
    albion.aiuplift
    neceros.tiertwotemp
    hanabishi.inwallcoolersandvents
    wemd.barbedwire
    owlchemist.undergroundpowerconduits
    neceros.mud
    proxyer.tinytable
    gguake.ui.simplesearchbar
    savestoragesettings.kv.rw
    falconne.bwm
    phomor.craftingqualityrebalanced
    tammybee.selectablesculpturegraphic
    erdelf.minifyeverything
    fluffy.fluffybreakdowns
    lingluo.lovelyhairstyle
    rimsenal.hair
    won.hair
    won2.hair
    vanillaexpanded.vhe
    nackbladinc.rimhair
    lf.frenzytime
    consolidatedtraits.kv.rw
    moretraitslots.kv.rw
    gewen.additionaltraits
    wemd.handsarenotoutside
    newsofpe.noresearch
    walkingproblem.noinfestation
    eagle0600.painscalesanity
    com.yayo.unlockworkingemperor
    pinochemicali.skilledstonecutting
    pinochemicali.moretradeships
    canicvs.turtlefriendlyraids
    bdew.romancetweaks
    fluffy.relationstab
    chjees.suprememelee
    grimm.unlimited
    fluffy.areaunlocker
    com.rimworld.nales.overcappedaccuracy
    paragon.hanul.utility
    etrt.cannibaltweaks
    jaxxa.ed.enhancedoptions
    tachyonite.pawnmorpher
    neronix17.fr.race.elves
    roskii.astoriel
    kikohi.forsakens
    sargoskar.witcherhunt
    vanillaexpanded.vaecd
    vanillaexpanded.vaets
    vanillaexpanded.vaetr
    vanillaexpanded.vaeis
    vanillaexpanded.vaebf
    vanillaexpanded.vaeed
    vanillaexpanded.vaeas
    vanillaexpanded.vaed
    vanillaexpanded.vaeau
    vanillaexpanded.vaet
    forsakens.fauna
    killface.colonistbarkf
    fluffy.thebirdsandthebees
    walkingproblem.wildanimalsex
    cucumpear.azrael.varietycoats
    neronix17.fr.faction.elves
    orion.factiondiscovery
    void.charactereditor
    edb.preparecarefully
    fluffy.blueprints
    fluffy.worktab

**Comment by FxWolfxe** [comment]
bug was caused by Portal Gun mod
