### ISSUE TITLE
[Feature] Improve performance by operating less often than every tick.

### ISSUE THREAD

**Issue by Vexthecollector** [Tachyonite/Pawnmorpher#813]
A lot of the performance heavy parts of Pawnmorpher like MutationTracker.CompTick() run every second, which can cause some slowdowns for games, as pawnmorpher will easy use up 1ms average with all its code, Mutationtracker.comptick for example uses 0.4ms on average already.

The Code inside it runs every second. Further code that spreads away is already staggered from what I can see, but it would be smarter to have the comptick itself be somewhat staggered. Instead of every tick, even just every second tick would be a lot more performant. Though I personally do not think that the mutations need to be updated that often.

Another patch that is rather unperformant seems to be Pawnmorph.HPatches.PawnPatches:FixIsColonist
I do not personally know how to improve this one. Could maybe be staggered too, though unsure if that would work well for a harmony patch.

These are just the two largest ones, but many other patches might work well with having a bit of delay, instead of running every singe tick.

**Comment by Zeracronius** [comment]
We are aware that comps have a major performance hit currently, but we are also actively working on sorting it.
See https://github.com/Tachyonite/Pawnmorpher/pull/780

I have FixIsColonist already listed in my todo as something that needs to be looked into and optimized.

Also MutationTracker.CompTick doesn't run every second, but every tick. This is 1x speed 60 times per second.

**Comment by Vexthecollector** [comment]
Ahh, I miss worded myself there. Meant once every tick.

And good to know those two are already being worked on. Gonna close thread then
