### ISSUE TITLE
Non-pack animal former humans cannot carry anything.

### ISSUE THREAD

**Issue by Zeracronius** [Tachyonite/Pawnmorpher#847]
**Describe the bug**
Former humans who are not pack animals can't carry anything in caravans. 
It feels like chaothrumbo should be able to carry quite a lot. 

Should this be based on sapience?

**Additional context**
https://discord.com/channels/603713246461165578/603713451633803274/1106019934284304395

**Comment by FxWolfxe** [comment]
yes, it should be based off of sapience. and on a related note, chaothrumbos should probably just be pack animals themselves like regular thrumbos

**Comment by Zeracronius** [comment]
> yes, it should be based off of sapience. and on a related note, chaothrumbos should probably just be pack animals themselves like regular thrumbos

As far as I can tell, regular thrumbos are not considered pack animals.

**Comment by FxWolfxe** [comment]
huh. might've been a mod I was using or just misremembering. nevermind then

**Comment by Zeracronius** [comment]
Probably https://steamcommunity.com/sharedfiles/filedetails/?id=2255432128
