### ISSUE TITLE
Mutation Log is only written by Chaomorph changes

### ISSUE THREAD

**Issue by Bbansjkl** [Tachyonite/Pawnmorpher#85]
**Describe the bug**
When a pawn is mutating, it seems only Chaomorph mutation results in a mutation log. Both "partial" and "changing" produce the log.  
Any other morph type, e.g. Alpacamorph (changing), doesn't write into the log about recently changed parts.

**To Reproduce**
1. Let a pawn that is not mutatagenic stabilised consume mutaserum, mutasyringe, chookmorph eggs or cowmorph milk
2. Open the pawns "Health" tab and wait for the first mutation to appear
3. Switch to the "Mutation" tab and open the log
4. Log is empty

**Error Log**
-

**Expected behavior**
Every mutation should write an entry into the mutation log

**Screenshots**
Screenshots of 5 pawns with the mutation method. Screenshots taken after all five pawns mutated at least once.
Kaori - Mutanite
![Kaori - Mutanite](https://user-images.githubusercontent.com/39167840/76350689-79a78300-630c-11ea-8173-baa32242d242.png)
Thomas - Chookmorph Eggs
![Thomas - Chookmorph Eggs](https://user-images.githubusercontent.com/39167840/76350691-7a401980-630c-11ea-97ce-6e708282098e.png)
Fabio - Cowmorph milk
![Fabio - Cowmorph milk](https://user-images.githubusercontent.com/39167840/76350692-7a401980-630c-11ea-991f-06d07c300c68.png)
Kezel - Chaobulb seedpod
![Kezel - Chaobulb seedpod](https://user-images.githubusercontent.com/39167840/76350693-7ad8b000-630c-11ea-9510-85f0d44eb484.png)
Ian - Mutasyringe, Alpaca
![Ian - Mutasyringe, Alpaca](https://user-images.githubusercontent.com/39167840/76350695-7ad8b000-630c-11ea-9b06-63156b8d6049.png)
Walls - Mutaserum
![Walls - Mutaserum](https://user-images.githubusercontent.com/39167840/76350697-7b714680-630c-11ea-9cd3-7e413f5255fe.png)

**Additional context**
Mods loaded were: Core, Humanoid Alien Races, PawnMorpher (in this order).

Attached savegames: Spawned five pawns, enclosed them with a wall and exposed them to mutation.
Savegame before just needs to be unpaused, consider letting the chook- and cowmorph and chaobulb pawns consume more to speed up the process.   
Savegame after is the state displayed in the screenshots above.

[PawnMorpher Log Bug.zip](https://github.com/Tachyonite/Pawnmorpher/files/4314346/PawnMorpher.Log.Bug.zip)

**Comment by Tachyonite** [comment]
Fixed in latest master update
