### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Me0w3rs** [Tachyonite/Pawnmorpher#852]
**Describe the bug**
When i enable the mod and try to load/create a map or dev quicktest, there's an error with map unable to load, or it just straight up disables all mods

**Mods Involved**
(AUTOSORTED)
1. Harmony
2. Core
3. Royalty
4. Ideology
5. Biotech
6. HugsLib
7. Humanoid Alien Races
8. Melee Animation
9. Vanilla Expanded Framework
10. Pawnmorpher
11. Wall light

**To Reproduce**
1. Go to 'mods'
2. Enable pawnmorpher, and the other mods needed for it to run (with additional mods does the same aswell)
3. Save and apply changes
4. Wait for the game to restart
5. See error

**Error Log**
(was too long, is in the .txt file included)

**Expected behavior**
I would download this mod with the ones it had required, then unzip and put them into the game's 'mods' folder. Then i would enable them and test the mod in 'dev quicktest' before creating a colony with the mod.

**Additional context**
(ERROR MESSAGE)
Recovered from incompatible or corrupted mods errors
it seems that some of the active mods were causing errors.

they were incompatible with eachother, designed for a different version of rimworld, or corrupted.

All mods have been disabled and can be activated in the mods dialog.
[Rimworld error log.txt](https://github.com/Tachyonite/Pawnmorpher/files/11472958/Rimworld.error.log.txt)

**Comment by Zeracronius** [comment]
Make sure to use the most recent version of the mod from workshop with the most recent version of the game available.
The github version is not compiled and will not work.

**Comment by Me0w3rs** [comment]
ah, okay, i'll try that out. thanks
