### ISSUE TITLE
100% Human to 100% Animal

### ISSUE THREAD

**Issue by SpookyFlan** [Tachyonite/Pawnmorpher#86]
X-Aspect pills were used to negate negative aspects but other than that nothing out of the ordinary was done with the pawn. No mutations formed throughout the whole process and the pawn progressed from completely human to completely animal after a certain amount of time. This change was not reflected in the mutations tab, as the pawn was labeled as 100% human until the transformation.

https://gist.github.com/80085c19fd437fc0772a0120b750635b

**Comment by FxWolfxe** [comment]
this should be fixed in the current version
