### ISSUE TITLE
Caravan animals will not flee to map border with me

### ISSUE THREAD

**Issue by Divwins** [Tachyonite/Pawnmorpher#889]
In any caravan encounter with at least one hostile on the map, a green line will appear on the entire map border. Pawns can be drafted and moved to this green border to flee the caravan encounter. When at least one pawn exits, every caravan animal will stop what they are doing and hurry to the border.

My animals are not doing this anymore. After _lots_ of trial and error, I traced it all the way back to Pawnmorpher. I even ran RimWorld with nothing but 4 mods: Pawnmorpher and its 3 required mods. When Pawnmorpher is installed, animals will not hurry to the border anymore when one person flees. They just keep doing whatever they are doing. This results in either the caravan encounter continuing to be loaded, or all caravan animals being lost along with the items they were holding. Simply removing Pawnmorpher makes the animals flee to the border again like intended.

I really like this mod and would like to use it without this problem. I imagine caravan fleeing is a more obscure mechanic, thus people have not been reporting this.

**Comment by Zeracronius** [comment]
This is indeed the first time I hear about this problem.
So far I haven't been able to pinpoint where this feature exists in Rimworld's code, and there's nothing obvious in the mod that should impact it.
The only alterations to animal behaviour should only apply to ones with sapience.

**Comment by Zeracronius** [comment]
I was not able to reproduce this behaviour even with just bare Core.
Turns out that what you experience also happens if Biotech is not present.

Now I can start looking into figuring out if anything interferes with that.
