### ISSUE TITLE
Wall of errors on game start,mod does not work

### ISSUE THREAD

**Issue by mc-oofy** [Tachyonite/Pawnmorpher#91]
**Describe the bug**
Mod does not work a metric ton of errors on game start

**Error Log**
If applicable the log of the error
[Player.log](https://github.com/Tachyonite/Pawnmorpher/files/4430994/Player.log)

**Expected behavior**
the game to run normally

**Comment by FxWolfxe** [comment]
It looks like your version of Pawnmorpher is either out of date or you're trying to run the 1.0 version of the mod on Rimworld 1.1.

**Comment by mc-oofy** [comment]
i am running the 1.1 mod on rimworld 1.1

**Comment by mc-oofy** [comment]
the dev branch i mean

**Comment by FxWolfxe** [comment]
the log states you're using the 1.7.3 mod version, the current dev and master version is 1.8, It also looks like HAR is failing to load as well, can you try building the latest version from github or using the current steam version and trying again? And if the errors persist can you post your mod order? Because this looks like more than just an issue with Pawnmorpher

**Comment by mc-oofy** [comment]
cant do steam version because im non-steam,trying to build now,gonna tell you the results
also HAR works fine without pawnmorpher

**Comment by mc-oofy** [comment]
(straight from save file) Mod List:
<modNames>
			<li>Harmony</li>
			<li>Core</li>
			<li>Royalty</li>
			<li>RimThemes</li>
			<li>HugsLib</li>
			<li>Humanoid Alien Races 2.0</li>
			<li>Android tiers</li>
			<li>Android tiers - TX Serie</li>
			<li>Pick Up And Haul</li>
			<li>Wall Light</li>
			<li>RunAndGun</li>
			<li>Rimatomics</li>
			<li>Dubs Mint Menus</li>
			<li>[KV] Show Hair With Hats or Hide All Hats - 1.1</li>
			<li>Interaction Bubbles</li>
			<li>Simple sidearms</li>
			<li>Dubs Bad Hygiene</li>
			<li>Mercenaries For Me</li>
			<li>Nature is Beautiful [1.0][1.1]</li>
			<li>[JPT] Open The Windows</li>
			<li>Genetic Rim</li>
			<li>RimBees</li>
			<li>RimBees - Genetic Rim Patch</li>
			<li>Dubs Skylights</li>
			<li>Door Mat</li>
			<li>MendAndRecycle</li>
			<li>Power++</li>
                        <li>Pawnmorpher</li>
			<li>SafeJobWorld</li>
			<li>FrameRateControl</li>
		</modNames>

**Comment by mc-oofy** [comment]
dev version seems to not contain 1.1 assemblies

**Comment by FxWolfxe** [comment]
You have to setup the repo in the Rimworld/Mods folder for the build script ot work, the resulting path should be something like Rimworld/Mods/Pawnmorpher. you may also need to build with Visual Studios at least once. You could also get the prebuild, steam version, on the discrod server (link on the steam page)

**Comment by mc-oofy** [comment]
the invite on the steam page is invalid

**Comment by FxWolfxe** [comment]
here's a temporary invite link to the latest build, try it with just HAR, harmony and hugs lib installed https://1drv.ms/u/s!AlvC0z21sTXRgphy7hHEDgUMq77ZOA?e=m2mUuD

**Comment by mc-oofy** [comment]
seems to work
