### ISSUE TITLE
Root level exception in OnGUI(): System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Spacedestructor** [Tachyonite/Pawnmorpher#911]
**Describe the bug**
When shooting a Humanoid Pawn with the Mutarifle and the resulting morphed animal becomes less Sapient while saving the game, then the save become corrupted.

**To Reproduce**
1. Mutate Humanoid Pawn (ideally using the Mutarifle).
2. Tame morphed Animal and assign to a pen or animal area.
3. Attempt to switch between Ui's that automatically close each other.
Optional Steps:
4. Save while the morphed animal is becomming less Sapient
5. Reload the Save just Made and repeat Step 3, it should persist through saving, loading and restarting the game.

**Error Log**
https://gist.github.com/HugsLibRecordKeeper/0cceb09c6341571ad8a5ed0aa8d247a0

**Expected behavior**
Expected the save to not get corrupted when saving while the morphed Animal is becomming less Sapient.

**Screenshots**

**Additional context**
Note: Some Modded Ui's such as [RimHud](https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027) and [[1001]Weapons Tab Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=2573988660) are more likely to trigger the "Root level exception in OnGUI()" but even with the Mods more likely to trigger it different Ui Windows have different chances and dont always trigger it.

**Comment by Zeracronius** [comment]
"Root level exception in OnGUI()" happens generally whenever any kind of UI throws errors. In this case it is BetterPawnControl, but LTS_Implants is also throwing errors.

If a save losses data on save, then usually an error happened while saving. The log only shows what is breaking after loading, rather than what potentially caused it in the first place.

Most likely it is a mod conflict.

**Comment by Zeracronius** [comment]
The only significant error i can see in that log is still BetterPawnControl

**Comment by Spacedestructor** [comment]
> The only significant error i can see in that log is still BetterPawnControl

Thank you very much, i have Removed BetterPawnControl for Testing and that reliably has resolved the Problem.
Seems to be an Incompatibility issue then.
