### ISSUE TITLE
Androids can be mutated

### ISSUE THREAD

**Issue by mc-oofy** [Tachyonite/Pawnmorpher#93]
**Describe the bug**
Androids from android tiers can be mutated
and while they are mutating i cant see their gizmos or make them do anything

**Error Log**
https://gist.github.com/a0be8f00de82878cc1f7b3b3a6d6770c

**Expected behavior**
androids shouldnt be able to get mutated

**Comment by FxWolfxe** [comment]
Androids morphing at all is a bug that I hope to have fixed soon, but it appears you are using an out of date version of HAF which is causing the gizmo bug
