### ISSUE TITLE
Feral Pawn doing plant cutting (Technically not possible I assume)

### ISSUE THREAD

**Issue by Martynas6ha4** [Tachyonite/Pawnmorpher#94]
hey! Just doing some general bug reporting

I'm using the 04-12 Version on pawnmorpher that I found on a thread around here since steam version for some reason refused to work.

Screenshot:

https://imgur.com/vBFr4Au

Active Modlist:
1/2: https://imgur.com/psvDCKB

2/2: https://imgur.com/kAq6hcP

**Comment by FxWolfxe** [comment]
This is working as intended. Sapient former humans will haul like human like pawns, so they will cut plants if they are hauling stuff to a construction site with plants on it even if plant cutting is disabled
