### ISSUE TITLE
Weird incompatibility

### ISSUE THREAD

**Issue by mc-oofy** [Tachyonite/Pawnmorpher#96]
**Describe the bug**
Im using the version that guy gave me,
RimThemes custom main menu background appearing when paused,
errors
(T5Research is of android tiers)
**Mod List**
```
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - aRandomKiwi.RimThemes
  - UnlimitedHugs.HugsLib
  - erdelf.HumanoidAlienRaces
  - Atlas.AndroidTiers
  - aRandomKiwi.AndroidTiersTXSerie
  - Mehni.PickUpAndHaul
  - Murmur.WallLight
  - roolo.RunAndGun
  - Dubwise.Rimatomics
  - Dubwise.DubsMintMenus
  - showhair.kv.rw
  - Jaxe.Bubbles
  - PeteTimesSix.SimpleSidearms
  - Dubwise.DubsBadHygiene
  - aRandomKiwi.MercenariesForMe
  - zhrocks11.NatureIsBeautiful
  - JPT.OpenTheWindows
  - sarg.rimbees
  - Dubwise.DubsSkylights
  - dracoix.doormat.r11a
  - notfood.MendAndRecycle
  - aRandomKiwi.PowerPP
  - sarg.alphaanimals
  - notfood.FrameRateControl
  - roolo.giddyupcore
  - roolo.giddyupcaravan
  - roolo.giddyuprideandroll
  - roolo.giddyupbattlemounts
  - Woolstrand.RealRuins
  - Cabbage.RimCities
  - Safe.Job.World
  - tachyonite.pawnmorpher
```

**Error Log**
[Player.log](https://github.com/Tachyonite/Pawnmorpher/files/4498748/Player.log)

**Comment by FxWolfxe** [comment]
It looks like you're not using the updated version of HAR

**Comment by mc-oofy** [comment]
how does that make the rimthemes main menu image appear when i pause

**Comment by FxWolfxe** [comment]
I don't know, but the old version of HAR is causing Pawnmorpher's initialization to fail. Those errors tend to cascade and cause all kinds of weird effects. Update your version of HAR and see if the error persists
